//! The egui control panel (the only egui UI outside the mode builders).

use crate::*;

/// Material Symbols glyph codepoints — GENERATED by `build.rs` from the font manifest (U.2.1), so the
/// glyphs the panel draws are exactly the ones subset into `MaterialSymbols-subset.ttf`. Do not edit.
#[allow(dead_code)] // ADD/DELETE/EYE/… are wired as button icons in U.2; generated as one set.
mod icons {
    include!(concat!(env!("OUT_DIR"), "/icon_glyphs.rs"));
}

/// The panel's outbound message writers, bundled so `panel_ui` spends ONE system param on all
/// three (Bevy caps a system at 16 params).
#[derive(SystemParam)]
pub(crate) struct PanelWriters<'w> {
    pub(crate) switch: MessageWriter<'w, SwitchFile>,
    pub(crate) autoplace: MessageWriter<'w, AutoPlace>,
    pub(crate) cmd: MessageWriter<'w, PanelCmd>,
    /// W.3.16 console UI state — folded in here (not a separate `panel_ui` param) to stay under Bevy's
    /// 16-param cap. The console CONTENT lives in a global buffer (`crate::console`), not the ECS.
    pub(crate) console: ResMut<'w, crate::console::ConsoleUi>,
    /// Z.3.3 inline file-rename state — likewise folded in to stay under the param cap.
    pub(crate) rename: ResMut<'w, RenameUi>,
    /// Z.3.10 inline rename of the hotchkiss.io ITEM's title (the document, not a file in it).
    pub(crate) item_rename: ResMut<'w, ItemRenameUi>,
}

/// The read-only display inputs the tabs render, bundled so `panel_ui` stays under Bevy's 16-param cap
/// (U.3). Grew as the Orientation/Export tabs (`print_pieces`, `copack`), the platform gate
/// (`platform`), and the pipeline feedback (`pipeline`) landed.
#[derive(SystemParam)]
pub(crate) struct PanelView<'w> {
    pub(crate) print_pieces: Res<'w, PrintPieces>,
    pub(crate) copack: Res<'w, CoPack>,
    pub(crate) platform: Res<'w, Platform>,
    pub(crate) pipeline: Res<'w, Pipeline>,
    /// The save-back target (W.5.7): `Some` ⇒ show the "Save to hotchkiss.io" affordance.
    pub(crate) save_target: Res<'w, SaveTarget>,
    /// The media ITEM (Z.3.10): `Some` ⇒ show the rename-on-the-site affordance.
    pub(crate) media_item: Res<'w, MediaItem>,
    /// Where the wordmark navigates home to (W.3.7.4): `Some` ⇒ it's a link, not a label.
    pub(crate) back_link: Res<'w, BackLink>,
    /// Self-update state (TB): a found update shows the header badge. `Option` because only the
    /// windowed app registers the resource — screenshot/scripted runs skip the update systems.
    #[cfg(target_os = "macos")]
    pub(crate) update: Option<Res<'w, crate::update::UpdateState>>,
    /// TG.1: the document's unsaved state — what Save, the markers and the Open hold gate on. Read-only
    /// since TG.3 moved Save out of `panel_ui` into `save_doc_action`.
    pub(crate) doc: Res<'w, DocState>,
}

/// One file's as-loaded customizer values: param name → value text.
type Defaults = std::collections::HashMap<String, String>;

/// The Customize tab's as-loaded defaults (X.2.4), per file of ONE document. TG.2: keyed by the
/// editor's owner as well as its path — a path alone aliases across documents (two same-stem
/// `.scadproj`s unpack to the same temp entry; a re-open reproduces its own paths), so a freshly
/// opened document showed the OLD one's defaults and Reset spliced them in. A new owner drops every
/// entry, so the map never outlives its document.
#[derive(Default)]
pub(crate) struct CustDefaults {
    owner: Option<crate::project::DocId>,
    by_path: std::collections::HashMap<std::path::PathBuf, Defaults>,
}

impl CustDefaults {
    /// Z.3.10: a rename MOVES the key. Without the move the renamed file misses its entry and the next
    /// capture records the buffer as it stands NOW — already customized — so Reset would forever reset
    /// to whatever was last dialled in.
    fn rename(&mut self, old: &std::path::Path, new: std::path::PathBuf) {
        if let Some(v) = self.by_path.remove(old) {
            self.by_path.insert(new, v);
        }
    }

    /// `path`'s defaults in `owner`'s document, captured through `read` the first time they're asked.
    fn capture(
        &mut self,
        owner: Option<crate::project::DocId>,
        path: &std::path::Path,
        read: impl FnOnce() -> Defaults,
    ) -> &Defaults {
        if owner != self.owner {
            self.by_path.clear();
            self.owner = owner;
        }
        self.by_path.entry(path.to_path_buf()).or_insert_with(read)
    }
}

/// Seconds of hold to fire a [`hold_to_confirm`] — long enough to be deliberate, short enough not to nag.
const HOLD_SECS: f32 = 0.6;

/// A hold's per-widget state (TG.2), kept in egui temp memory under the widget's id.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
struct Hold {
    /// Charge in `0..=1`.
    prog: f32,
    /// Fired and the pointer is still down: no re-arm until a release. Without the latch a long hold
    /// recharges and fires AGAIN — and a row delete's id is the row INDEX, so after the list shifts up
    /// the second fire deletes the NEXT file.
    latched: bool,
}

impl Hold {
    /// One frame of the charge (the testable half of [`hold_to_confirm`]): fills over [`HOLD_SECS`]
    /// while `held`, drains twice as fast once released (a flicked press must not leave a half-charged
    /// button for next time). Returns the next state and whether it FIRED: a full charge fires once,
    /// then latches empty until the pointer lets go.
    fn step(self, dt: f32, held: bool) -> (Hold, bool) {
        if self.latched {
            let next = Hold {
                prog: 0.0,
                latched: held,
            };
            return (next, false);
        }
        let prog = if held {
            self.prog + dt / HOLD_SECS
        } else {
            self.prog - dt / (HOLD_SECS * 0.5)
        }
        .clamp(0.0, 1.0);
        if prog >= 1.0 {
            (
                Hold {
                    prog: 0.0,
                    latched: true,
                },
                true,
            )
        } else {
            (
                Hold {
                    prog,
                    latched: false,
                },
                false,
            )
        }
    }
}

/// A press-and-HOLD confirm (no modal — chotchki hates them; TG.2 generalized it from the delete): a
/// button that FILLS as you hold it — danger-red for a destructive act, gold otherwise; release early
/// and the fill drains, hold to full and it fires (returns `true` that frame). A plain click never
/// fires. The hold progress lives in egui memory keyed by `id` (transient, per-widget), so it needs no
/// Bevy param — `panel_ui` is at its 16-param cap. The caller builds the `button` (glyph or text, small
/// or not); right-align its layout to seat a row action at the edge.
fn hold_to_confirm(
    ui: &mut egui::Ui,
    id: egui::Id,
    button: egui::Button<'_>,
    hover: &str,
    danger: bool,
) -> bool {
    let resp = ui.add(button).on_hover_text(hover);
    let dt = ui.input(|i| i.stable_dt);
    let prev: Hold = ui.data(|d| d.get_temp(id).unwrap_or_default());
    let (hold, fired) = prev.step(dt, resp.is_pointer_button_down_on());
    let prog = hold.prog;
    if resp.is_pointer_button_down_on() || prog > 0.0 {
        ui.ctx().request_repaint(); // animate the fill while held, and while it drains
    }
    // The charging fill: a translucent sweep left→right across the button, label showing through.
    if prog > 0.0 {
        let r = resp.rect;
        let fill = egui::Rect::from_min_size(r.min, egui::vec2(r.width() * prog, r.height()));
        let [cr, cg, cb, _] = if danger { theme::DANGER } else { theme::GOLD }.to_array();
        ui.painter().rect_filled(
            fill,
            2.0,
            egui::Color32::from_rgba_unmultiplied(cr, cg, cb, 110),
        );
    }
    ui.data_mut(|d| d.insert_temp(id, hold));
    fired
}

/// TG.2: egui keeps the code editor's cursor AND undo history (whole-text snapshots) under its widget
/// id, so right after an open or a file switch Cmd+Z put the PREVIOUS file's text into this one. Drop
/// that state whenever the buffer changes hands: another document or another file. A rename or a
/// Save As re-points the path, so it loses the undo history too; that costs less than a leak.
fn forget_foreign_history(
    ctx: &egui::Context,
    id: egui::Id,
    owner: Option<crate::project::DocId>,
    path: &std::path::Path,
) {
    let key = id.with("held_by");
    let now = (owner, path.to_path_buf());
    if ctx
        .data(|d| d.get_temp::<(Option<crate::project::DocId>, std::path::PathBuf)>(key))
        .as_ref()
        != Some(&now)
    {
        ctx.data_mut(|d| {
            d.remove::<egui::text_edit::TextEditState>(id);
            d.insert_temp(key, now);
        });
    }
}

/// TG.7: the UNSAVED marker — a painter-drawn FILLED circle. The stale marker stays `icons::DOT`, which
/// the FILL=0 font subset renders as a RING, so the two differ in shape (spec: "Unsaved and stale look
/// different") with no font regeneration and no tofu risk. Hover text is the caller's.
fn unsaved_marker(ui: &mut egui::Ui) -> egui::Response {
    const D: f32 = 9.0;
    let (rect, resp) = ui.allocate_exact_size(egui::vec2(D, D), egui::Sense::hover());
    ui.painter()
        .circle_filled(rect.center(), D * 0.5, theme::GOLD_DIM);
    resp
}

/// The whole control panel (U.3), immediate-mode: an app-wide top tab bar + bottom status bar +
/// a left egui panel whose contents route on the active `Tab` (Model / Parts / Orientation / Export).
/// Cheap edits mutate in place; a heavy action (needing params beyond the panel's own) writes a
/// `PanelCmd` its dedicated system handles. Writes `PanelSeam` after drawing so `orbit` yields the
/// pointer over the panels and `split_viewport` insets the 3D camera inside all three bars.
#[allow(clippy::too_many_arguments)]
// On wasm the desktop-only file picker is gated out, so `open_dialog` is read but never written there.
#[cfg_attr(target_arch = "wasm32", allow(unused_mut))]
pub(crate) fn panel_ui(
    mut contexts: EguiContexts,
    mut parts: ResMut<Parts>,
    mut active_part: ResMut<ActivePart>,
    mut active: ResMut<ActiveConn>,
    mut edit: ResMut<EditCut>,
    mut tab: ResMut<Tab>,
    project: Res<crate::project::ProjectDoc>,
    status: Res<Status>,
    mut open_dialog: ResMut<OpenDialog>,
    mut editor: ResMut<EditorBuf>,
    mut scene: ResMut<SceneCfg>,
    time: Res<Time>,
    view: PanelView,
    mut writers: PanelWriters,
    mut seam: ResMut<PanelSeam>,
    // X.2.4 reset-to-default: per-file map of param name → as-loaded value. A `Local` (not a resource)
    // so it needs no per-app init and captures automatically in every app that runs `panel_ui`.
    mut cust_defaults: Local<CustDefaults>,
) {
    let Ok(ctx) = contexts.ctx_mut() else {
        return;
    };
    // W.3.40: Cmd/Ctrl+S saves, from ANY tab — COMMAND is egui's platform primary (Cmd on macOS, Ctrl
    // elsewhere). Consumed unconditionally (so the editor never also sees it) and sent unconditionally:
    // TG.3's `save_doc_action` answers a clean document with "nothing to save" instead of a silent
    // no-op. Checked before the tab match so it fires even when no Save button is on screen. On web
    // the browser's own save-page dialog is already suppressed by the window's
    // `prevent_default_event_handling` (see clipboard.rs).
    // TG.5: Cmd/Ctrl+Shift+S is Save As on a desktop, checked FIRST — `consume_key` matches modifiers
    // logically (an unrequested Shift is ignored), so the plain chord would swallow the shifted one.
    // The web has no Save As (Save downloads), so there the shifted chord falls through to Save.
    if view.platform.shows_picker()
        && ctx.input_mut(|i| {
            i.consume_key(
                egui::Modifiers::COMMAND | egui::Modifiers::SHIFT,
                egui::Key::S,
            )
        })
    {
        writers.cmd.write(PanelCmd::SaveAs);
    } else if ctx.input_mut(|i| i.consume_key(egui::Modifiers::COMMAND, egui::Key::S)) {
        writers.cmd.write(PanelCmd::Save);
    }
    // X.2: the customizer params for the current buffer (owned, so it doesn't hold `editor`'s borrow).
    // Drives the conditional Customize tab + its widgets. Cheap — `customize` parses only the buffer.
    let cv_params = crate::customize::extract(&editor.text);
    // Z.3.10: the renaming handler is a different system and can't reach a `Local`, so it reports the
    // move and the defaults' key follows it here (see [`CustDefaults::rename`]).
    // TG.5: a Save As re-home moves every file at once, so the moves queue.
    for (old, new) in writers.rename.renamed.drain(..) {
        cust_defaults.rename(&old, new);
    }
    // Capture the as-loaded defaults the first time we see this file of this DOCUMENT (first frame ⇒
    // still the file's own values, before any customization) — see [`CustDefaults`].
    let cv_defaults = Some(cust_defaults.capture(editor.owner, &editor.path, || {
        cv_params
            .iter()
            .map(|p| {
                let v = editor
                    .text
                    .get(p.value_span.clone())
                    .unwrap_or("")
                    .trim()
                    .to_string();
                (p.name.clone(), v)
            })
            .collect()
    }));
    // TG.7: the document as every surface names it — the header chip, the Project card, the Save hover —
    // all from the route Save actually takes (`save_route`), so none can promise what Save doesn't do.
    let home = crate::file_ops::home_dir();
    let on_site = view.save_target.0.is_some();
    let route = crate::save::save_route(&project, *view.platform, on_site);
    let card = crate::doc_view::doc_card(&project, &route, on_site, home.as_deref());
    let save_hover = crate::save::plan_line(&route, home.as_deref());
    // A delete defers past the row loop (index stability), tagged with the PART it belongs to (T.2b).
    let mut to_remove: Option<(usize, usize)> = None;
    // A per-piece "reset to auto" (U.3.4) likewise defers past the Orientation list's `parts` borrow.
    let mut reset_orient: Option<(usize, PieceKey)> = None;
    // egui 0.35 panels show INTO a Ui, not the Context — wrap the viewport in a background-layer Ui
    // first (the bevy_egui side_panel pattern) so the panels overlay the 3D view.
    let mut viewport = egui::Ui::new(
        ctx.clone(),
        egui::Id::new("panel_viewport"),
        egui::UiBuilder::new()
            .layer_id(egui::LayerId::background())
            .max_rect(ctx.viewport_rect()),
    );
    // Heavy navy-bordered div-grey card, 8px pad — the site's chrome surface. Every bar/panel uses it.
    let panel_frame = || {
        egui::Frame::new()
            .fill(theme::DIV_GREY)
            .stroke(egui::Stroke::new(2.0, theme::NAVY))
            .inner_margin(egui::Margin::same(8))
    };
    // TOP BAR (U.3): the workflow tabs — Model → Parts → Orientation → Export. Each is a navy pill (the
    // site's nav); the ACTIVE one is gold-lettered with a gold underline (the retired green is gone).
    let top = egui::Panel::top("topbar")
        .frame(panel_frame())
        .show(&mut viewport, |ui| {
            ui.horizontal(|ui| {
                // W.3.7.4: with a `?back=` the wordmark IS the way home. A host that hands the tool the
                // whole viewport has no nav left on screen, so the app has to carry it — and the
                // wordmark is where a user already looks for "back to the site". Without one it stays
                // the plain label it has always been (every desktop run, and any embed that keeps its
                // own chrome), so this adds a control only where one is actually missing.
                match view.back_link.0.as_deref() {
                    Some(url) => {
                        // Reachable only on the web — `BackLink` has no source on desktop (no page URL),
                        // so it is always None there and this arm never runs.
                        #[cfg(not(target_arch = "wasm32"))]
                        let _ = url;
                        if ui
                            .add(
                                egui::Label::new(theme::chrome("fab-gui", 22.0).color(theme::NAVY))
                                    .sense(egui::Sense::click()),
                            )
                            .on_hover_text("back to the site")
                            .clicked()
                        {
                            #[cfg(target_arch = "wasm32")]
                            crate::web_host::navigate(url);
                        }
                    }
                    None => {
                        ui.label(theme::chrome("fab-gui", 22.0).color(theme::NAVY));
                    }
                }
                // the site's serif voice — a Quattrocento tagline beside the wordmark
                ui.label(
                    egui::RichText::new("slice · orient · pack")
                        .font(theme::quattro(13.0))
                        .color(theme::TEXT_MUTED),
                );
                // TG.7: the document chip — its name on every tab (nothing outside the Project tab used
                // to say what was open), the unsaved marker, the full location on hover; a click goes
                // to the Project tab, where the card and Save live.
                let chip = ui
                    .add(
                        egui::Button::new(
                            egui::RichText::new(card.name.as_str())
                                .size(14.0)
                                .color(theme::NAVY),
                        )
                        .fill(theme::FAINT_BG)
                        .stroke(egui::Stroke::new(1.0, theme::BORDER_SUBTLE)),
                    )
                    .on_hover_text(format!("{} — open the Project tab", card.full));
                if chip.clicked() {
                    *tab = Tab::Project;
                }
                if view.doc.dirty {
                    unsaved_marker(ui).on_hover_text("unsaved changes");
                }
                ui.separator();
                // The Customize tab (X.2) slots in after Model, but ONLY when the model exposes
                // parameters — an empty customizer is a wart, so the tab appears with the content.
                let mut bar: Vec<(Tab, &'static str)> = Vec::with_capacity(6);
                // Project is always first (Phase Z) — the document's files live here, ahead of the pipeline.
                bar.push((Tab::Project, "Project"));
                for (t, label) in Tab::ALL {
                    bar.push((t, label));
                    if t == Tab::Model && !cv_params.is_empty() {
                        bar.push((Tab::Customize, "Customize"));
                    }
                }
                for (t, label) in bar {
                    let on = *tab == t;
                    let caption = theme::chrome(label, 15.0).color(if on {
                        theme::GOLD
                    } else {
                        theme::DIV_GREY
                    });
                    let resp = ui.add(egui::Button::new(caption).fill(theme::NAVY));
                    if on {
                        // the site's signature: a gold underline on the active tab
                        ui.painter().hline(
                            resp.rect.x_range(),
                            resp.rect.bottom() - 1.0,
                            egui::Stroke::new(2.0, theme::GOLD),
                        );
                    }
                    if resp.clicked() {
                        *tab = t;
                    }
                    // Per-node feedback (U.3.7): a gold spinner while THIS stage computes (fires on the
                    // first render too), else a GOLD_DIM stale dot when its output is behind its input.
                    if view.pipeline.loading[t.index()] {
                        ui.add(egui::Spinner::new().size(12.0).color(theme::GOLD));
                    } else if view.pipeline.dirty[t.index()] {
                        // icons::DOT (Material Symbols), NOT a raw bullet — the font stack would tofu it.
                        ui.colored_label(theme::GOLD_DIM, icons::DOT);
                    }
                }
                // W.3.27: the Settings gear, pushed to the far RIGHT of the header. Desktop only — the
                // web has no publish key to set (its save-back rides the site session). icons::SETTINGS
                // is a Material Symbols glyph (a raw ⚙ would tofu — see gui/CLAUDE.md).
                // Right-align the gear the same way `console::controls` right-aligns the Console button.
                // (egui's two-pass sizing logs a benign "changed id between passes" for right-aligned
                // widgets — a pre-existing quirk the Console button shares; the interaction is fine.)
                #[cfg(not(target_arch = "wasm32"))]
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    let gear = egui::Button::new(
                        egui::RichText::new(icons::SETTINGS)
                            .size(16.0)
                            .color(theme::DIV_GREY),
                    )
                    .fill(theme::NAVY);
                    if ui
                        .add(gear)
                        .on_hover_text("Settings — hotchkiss.io publish key")
                        .clicked()
                    {
                        writers.cmd.write(PanelCmd::OpenSettings);
                    }
                    // TB: the self-update badge — gold, left of the gear, only while an update is
                    // ready. chrome() uppercases; the version digits are ASCII, no tofu risk.
                    #[cfg(target_os = "macos")]
                    if let Some(v) = view.update.as_ref().and_then(|u| u.found_version()) {
                        let badge = egui::Button::new(
                            theme::chrome(format!("update {v}"), 13.0).color(theme::NAVY),
                        )
                        .fill(theme::GOLD);
                        if ui
                            .add(badge)
                            .on_hover_text("A new version is ready — click to install")
                            .clicked()
                        {
                            writers.cmd.write(PanelCmd::OpenUpdate);
                        }
                    }
                });
            });
        });
    // BOTTOM BAR (U.3): the status line — a gold spinner + navy activity label while a job runs (the
    // pipeline's ACCURATE activity, never the possibly-stale imperative `Status`); the imperative
    // status shows only when idle (the last result / error / "ready").
    // W.3.16: the status bar expands into a CONSOLE. Collapsed = one status row; expanded = a resizable
    // panel with the echo/warnings (+ optional tracing) below. Size decided from last frame's state so
    // the panel height and its content agree (a fresh toggle lands next frame — imperceptible).
    let console_expanded = writers.console.expanded;
    let mut statusbar = egui::Panel::bottom("statusbar").frame(panel_frame());
    if console_expanded {
        statusbar = statusbar
            .resizable(true)
            .default_size(220.0)
            .min_size(96.0)
            .max_size(480.0);
    }
    let bottom = statusbar.show(&mut viewport, |ui| {
        // Status ROW: the pipeline's accurate activity while busy (never the possibly-stale imperative
        // Status), else the imperative status — with the console controls right-aligned.
        ui.horizontal(|ui| {
            // Right-align the controls FIRST so a long status — a W.3.37 "line N: assertion failed […]"
            // can run long — can't shove Draft/Final + the console controls off the screen. The status then
            // TRUNCATES into whatever width is left (the full text still lives in the console).
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                crate::console::controls(ui, &mut writers.console);
                // W.3.25.2: live-view quality — Draft (fast) / Final (see the real smoothness). Session-only;
                // export always renders Final. Flipping it re-renders the buffer (bumps edited_at).
                let mut want_final = crate::render_quality::is_final();
                let before = want_final;
                // right_to_left lays out in reverse, so add Final THEN Draft to read "Draft Final" L→R.
                ui.selectable_value(&mut want_final, true, "Final");
                ui.selectable_value(&mut want_final, false, "Draft");
                if want_final != before {
                    crate::render_quality::set(want_final);
                    editor.edited_at = Some(time.elapsed_secs_f64());
                }
                ui.separator();
                // The leftover width (left): the status/activity, truncated so it never pushes the controls.
                ui.with_layout(
                    egui::Layout::left_to_right(egui::Align::Center),
                    |ui| match &view.pipeline.activity {
                        Some(activity) if view.pipeline.busy => {
                            ui.add(egui::Spinner::new().size(14.0).color(theme::GOLD));
                            ui.add(
                                egui::Label::new(
                                    egui::RichText::new(activity.as_str()).color(theme::NAVY),
                                )
                                .truncate(),
                            );
                            ui.ctx().request_repaint();
                        }
                        _ => {
                            ui.add(egui::Label::new(status.0.as_str()).truncate());
                        }
                    },
                );
            });
        });
        if console_expanded {
            ui.separator();
            crate::console::log_view(ui, writers.console.full, writers.console.level);
        }
    });
    // LEFT PANEL (U.3): the active tab's controls.
    let panel = egui::Panel::left("panel")
        .resizable(true)
        .default_size(440.0)
        .frame(panel_frame())
        .show(&mut viewport, |ui| {
            match *tab {
                Tab::Project => {
                    // TG.7: the DOCUMENT card leads the tab — name, place · kind, what Save does here, and
                    // Save / Save As… / Open… — so "what is open and how do I save it" is answered before
                    // the file list. The old one-line hint was zip trivia for a `.scadproj` and told a
                    // fresh multi-file document it "saves in place". The text is `doc_view`'s (tested).
                    ui.horizontal(|ui| {
                        ui.label(
                            egui::RichText::new(card.name.as_str())
                                .size(16.0)
                                .color(theme::NAVY)
                                .strong(),
                        )
                        .on_hover_text(card.full.as_str());
                        if view.doc.dirty {
                            unsaved_marker(ui).on_hover_text("unsaved changes");
                        }
                    });
                    for line in [&card.place, &card.save_rule] {
                        ui.label(
                            egui::RichText::new(line.as_str())
                                .font(theme::quattro(12.0))
                                .color(theme::TEXT_MUTED),
                        );
                    }
                    ui.horizontal(|ui| {
                        // Save: gold and enabled while unsaved, grey and disabled when clean (the macOS
                        // default; chotchki, 2026-10-05). Same `PanelCmd::Save` as Cmd/Ctrl+S.
                        let dirty = view.doc.dirty;
                        let caption = theme::chrome("Save", 14.0);
                        let save = if dirty {
                            egui::Button::new(caption.color(theme::NAVY)).fill(theme::GOLD)
                        } else {
                            egui::Button::new(caption)
                        };
                        if ui
                            .add_enabled(dirty, save)
                            .on_hover_text(save_hover.as_str())
                            .on_disabled_hover_text(crate::save::nothing_line(&project))
                            .clicked()
                        {
                            writers.cmd.write(PanelCmd::Save);
                        }
                        // TG.5: Save As… for EVERY desktop document (it replaced Z.3.7's gold promote).
                        // The hover names the file kind it writes — `.scad` for one file, `.scadproj`
                        // otherwise; the kind walks a loose folder for assets, so only while hovered.
                        if view.platform.shows_picker()
                            && ui
                                .button("Save As…")
                                .on_hover_ui(|ui| {
                                    let ext = crate::save::SaveAsKind::of(
                                        &project,
                                        crate::save::has_disk_assets(&project),
                                    )
                                    .ext();
                                    ui.label(format!(
                                        "write this document to a new .{ext} and keep working \
                                         there — the original stays as it was"
                                    ));
                                })
                                .clicked()
                        {
                            writers.cmd.write(PanelCmd::SaveAs);
                        }
                        // TG.2: an open REPLACES the document (adopt), so while it's unsaved Open… asks
                        // for a hold — never a modal — and a plain click does nothing. OPEN is
                        // desktop-only: on the web the document is whatever `?model=` handed us, and
                        // swapping it out would orphan the save-back target. TG.7: text-only — it used
                        // to share Add…'s `+` glyph.
                        let open = view.platform.shows_picker()
                            && if view.doc.dirty {
                                hold_to_confirm(
                                    ui,
                                    egui::Id::new("proj_open_discard"),
                                    egui::Button::new("hold to discard changes and open…"),
                                    "this document has unsaved changes — hold to discard them and \
                                     open a .scad model or a .scadproj project",
                                    true,
                                )
                            } else {
                                ui.button("Open…")
                                    .on_hover_text("open a .scad model or a .scadproj project")
                                    .clicked()
                            };
                        if open && open_dialog.0.is_none() {
                            #[cfg(not(target_arch = "wasm32"))]
                            {
                                open_dialog.0 =
                                    Some(AsyncComputeTaskPool::get().spawn(async move {
                                        rfd::AsyncFileDialog::new()
                                            .add_filter(
                                                "OpenSCAD source or project",
                                                &["scad", "scadproj"],
                                            )
                                            .pick_file()
                                            .await
                                            .map(|h| h.path().to_path_buf())
                                    }));
                            }
                        }
                    });
                    // Z.3.10: rename the ITEM on hotchkiss.io — the DOCUMENT's name (what the gallery
                    // shows and what every future download/publish is called), as opposed to the file
                    // rows below, which rename files INSIDE it. Gated on a derived MediaItem, exactly
                    // like the Save button: the app can't know it's an admin without another round
                    // trip, so it attempts the write and reports a 401/403 plainly.
                    if view.media_item.0.is_some() {
                        if writers.item_rename.editing {
                            ui.horizontal(|ui| {
                                let resp = ui.add(
                                    egui::TextEdit::singleline(&mut writers.item_rename.buf)
                                        .desired_width(220.0),
                                );
                                if writers.item_rename.focus {
                                    resp.request_focus();
                                    writers.item_rename.focus = false;
                                }
                                let enter = ui.input(|inp| inp.key_pressed(egui::Key::Enter));
                                let esc = ui.input(|inp| inp.key_pressed(egui::Key::Escape));
                                if esc {
                                    writers.item_rename.editing = false;
                                } else if resp.lost_focus() {
                                    if enter {
                                        writers.item_rename.commit =
                                            Some(writers.item_rename.buf.clone());
                                        writers.cmd.write(PanelCmd::RenameOnSite);
                                    }
                                    writers.item_rename.editing = false; // commit-on-enter or cancel-on-blur
                                }
                            });
                        } else if ui
                            .small_button("Rename on hotchkiss.io…")
                            .on_hover_text("change this model's title on the site (admin only)")
                            .clicked()
                        {
                            // Seed with the CURRENT name, minus its extension — the field edits a
                            // title, not a filename.
                            writers.item_rename.buf = project.doc_stem().unwrap_or_default();
                            writers.item_rename.editing = true;
                            writers.item_rename.focus = true;
                        }
                    }
                    // Self-documenting: the gold ▸ is the render target; a navy ▸ button moves it.
                    if project.files.len() > 1 {
                        ui.label(
                            egui::RichText::new(format!(
                                "{} marks what renders — click a file's {} to make it the target",
                                icons::CHEVRON_RIGHT,
                                icons::CHEVRON_RIGHT
                            ))
                            .font(theme::quattro(11.0))
                            .color(theme::TEXT_MUTED),
                        );
                    }
                    ui.separator();
                    // File rows: the entry carries the GOLD render-pointer (a static label); every OTHER
                    // row leads with a NAVY ▸ button that promotes it to the render target. The active
                    // (editor-shown) row is the selected pill; a dirty file shows the unsaved marker; a red
                    // trash button removes it (never the entry, never the last file).
                    let multi = project.files.len() > 1;
                    // Z.3.10: file MANAGEMENT (rename / set-entry / delete) is available on BOTH
                    // platforms now — every one of these is a pure ProjectDoc edit, handled natively by
                    // `project_files_action` and on the web by `project_files_action_web`. Only the
                    // genuinely fs-bound affordances below still ask `shows_picker()`.
                    let manage = view.platform.manages_files();
                    for (i, f) in project.files.iter().enumerate() {
                        ui.horizontal(|ui| {
                            let is_entry = i == project.entry;
                            if is_entry {
                                ui.label(egui::RichText::new(icons::CHEVRON_RIGHT).color(theme::GOLD))
                                    .on_hover_text("entry — the project's render target");
                            } else if manage {
                                if ui
                                    .add(
                                        egui::Button::new(
                                            egui::RichText::new(icons::CHEVRON_RIGHT)
                                                .color(theme::NAVY),
                                        )
                                        .small(),
                                    )
                                    .on_hover_text("set as the render target (entry)")
                                    .clicked()
                                {
                                    writers.cmd.write(PanelCmd::SetEntry(i));
                                }
                            } else {
                                ui.add_space(14.0); // align names under the entry pointer
                            }
                            // Name cell: a text field while renaming THIS row (double-click to start,
                            // Enter commits, Esc / click-away cancels), else the selectable pill.
                            if manage && writers.rename.editing == Some(i) {
                                let resp = ui.add(
                                    egui::TextEdit::singleline(&mut writers.rename.buf)
                                        .desired_width(180.0),
                                );
                                if writers.rename.focus {
                                    resp.request_focus();
                                    writers.rename.focus = false;
                                }
                                let enter = ui.input(|inp| inp.key_pressed(egui::Key::Enter));
                                let esc = ui.input(|inp| inp.key_pressed(egui::Key::Escape));
                                if esc {
                                    writers.rename.editing = None;
                                } else if resp.lost_focus() {
                                    if enter {
                                        writers.rename.commit =
                                            Some((i, writers.rename.buf.clone()));
                                    }
                                    writers.rename.editing = None; // commit-on-enter or cancel-on-blur
                                }
                            } else {
                                let resp = ui.selectable_label(project.active == i, &f.name);
                                if resp.clicked() {
                                    writers.switch.write(SwitchFile(i));
                                }
                                if manage
                                    && resp
                                        .on_hover_text("double-click to rename")
                                        .double_clicked()
                                {
                                    writers.rename.editing = Some(i);
                                    writers.rename.buf = f.name.clone();
                                    writers.rename.focus = true;
                                }
                            }
                            // TG.1: stored OR live edits — the active row marks as you type.
                            if project.file_unsaved(i, &editor) {
                                unsaved_marker(ui).on_hover_text("unsaved");
                            }
                            // Delete: RIGHT-aligned column, HOLD to fire (destructive → deliberate).
                            if manage && multi && !is_entry {
                                ui.with_layout(
                                    egui::Layout::right_to_left(egui::Align::Center),
                                    |ui| {
                                        if hold_to_confirm(
                                            ui,
                                            egui::Id::new(("proj_del", i)),
                                            egui::Button::new(
                                                egui::RichText::new(icons::DELETE)
                                                    .color(theme::DANGER),
                                            )
                                            .small(),
                                            // TG.6: loose delete is session-only — say so.
                                            crate::file_ops::delete_hover(&project),
                                            true,
                                        ) {
                                            writers.cmd.write(PanelCmd::DeleteFile(i));
                                        }
                                    },
                                );
                            }
                        });
                    }
                    // Binary assets ride along (import()/surface()) — listed, not editable.
                    for name in project.assets.keys() {
                        ui.horizontal(|ui| {
                            ui.add_space(14.0);
                            ui.label(
                                egui::RichText::new(name.as_str()).color(theme::TEXT_MUTED),
                            )
                            .on_hover_text("binary asset (import/surface) — rides the project, not editable");
                            // TG.1/TG.7: an added binary is unsaved too, with the same filled marker.
                            if project.asset_unsaved(name) {
                                unsaved_marker(ui).on_hover_text("unsaved");
                            }
                        });
                    }
                    ui.separator();
                    // Add/New, below the rows they extend, on BOTH platforms (Z.3.10) — Add reads bytes
                    // through the browser's own file input on web and rfd on desktop, New is a pure
                    // ProjectDoc edit; both write a PanelCmd that `project_files_action{,_web}` handles.
                    // (Open… and Save As… live on the document card above, TG.7.)
                    ui.horizontal(|ui| {
                        if ui
                            .button(format!("{}  Add…", icons::ADD))
                            // TG.6: a loose Add writes into the real folder — say so up front.
                            .on_hover_text(crate::file_ops::add_hover(&project))
                            .clicked()
                        {
                            writers.cmd.write(PanelCmd::AddFiles);
                        }
                        if ui
                            .button("New file")
                            .on_hover_text("add a new empty .scad")
                            .clicked()
                        {
                            writers.cmd.write(PanelCmd::NewFile);
                        }
                    });
                }
                Tab::Model => {
                    // TG.7: the breadcrumb — which file is in the editor, which document it's in, and
                    // which file renders when that isn't this one (the viewport keeps drawing the entry,
                    // and Customize follows the VIEWED file, so the tab has to say both).
                    ui.label(
                        egui::RichText::new(crate::doc_view::breadcrumb(&project))
                            .font(theme::quattro(12.0))
                            .color(theme::TEXT_MUTED),
                    );
                    // Save (explicit): the buffer renders live, but the file on disk only changes here or
                    // via Cmd/Ctrl+S (W.3.40). Both send `PanelCmd::Save`; where it writes and what it
                    // reports is `save::save_doc_action` (TG.3).
                    ui.horizontal(|ui| {
                        // TG.4: the hover says where THIS document's Save goes (`save_route` — the
                        // same table `save_doc_action` routes by), e.g. "download Brace.scadproj"; the
                        // old fixed "download .scad" was wrong for every project. TG.7: labelled — an
                        // icon-only floppy didn't read as the way to save.
                        if ui
                            .add_enabled(
                                view.doc.dirty,
                                egui::Button::new(format!("{}  Save", icons::SAVE)),
                            )
                            .on_hover_text(save_hover.as_str())
                            .on_disabled_hover_text(crate::save::nothing_line(&project))
                            .clicked()
                        {
                            writers.cmd.write(PanelCmd::Save);
                        }
                        // TG.1: the DOCUMENT's state — a clean view of an unsaved project still says so.
                        // TG.7: the filled marker, never the stale ring.
                        if view.doc.dirty {
                            unsaved_marker(ui);
                            ui.colored_label(theme::GOLD_DIM, "unsaved");
                        }
                        // Set-entry from the editor (Z.3.6): viewing a file that ISN'T the render
                        // target, one click makes it the entry — no trip back to the Project tab.
                        // Both platforms since Z.3.10 — `project_files_action_web` handles SetEntry
                        // in the browser.
                        if view.platform.manages_files()
                            && project.is_multifile()
                            && project.active != project.entry
                            && ui
                                .add(
                                    egui::Button::new(
                                        theme::chrome("Set as entry", 13.0).color(theme::NAVY),
                                    )
                                    .fill(theme::GOLD),
                                )
                                .on_hover_text("render THIS file as the project's entry point")
                                .clicked()
                        {
                            writers.cmd.write(PanelCmd::SetEntry(project.active));
                        }
                    });
                    // Save back to the site (W.5.8): web only, and only when the deep-link named a media
                    // item (else there's no item to update in place). Z.3.8: a project PUTs its whole
                    // `.scadproj` now (the guard is gone). Gold CTA; the status bar reports progress.
                    if view.save_target.0.is_some()
                        && ui
                            .add(
                                egui::Button::new(
                                    theme::chrome("Save to hotchkiss.io", 14.0).color(theme::NAVY),
                                )
                                .fill(theme::GOLD),
                            )
                            .on_hover_text(crate::save::plan_line(
                                &crate::save::plan(&project, *view.platform, true),
                                None,
                            ))
                            .clicked()
                    {
                        writers.cmd.write(PanelCmd::SaveToSite);
                    }
                    // The code editor — its buffer IS the render source (debounced preview, U.3.2).
                    // `auto_shrink` off + sizing to the remaining space so it FILLS the panel, not just
                    // the text height (else a short file leaves the panel half-empty). `both()` (not
                    // `vertical()`) so a long line SCROLLS horizontally inside the editor instead of
                    // pushing the resizable panel wider — the code editor scrolls, never wraps
                    // (highlight::scad_job), and without a horizontal bar the over-wide galley set the
                    // panel's min width and a drag-narrow snapped straight back.
                    egui::ScrollArea::both()
                        .auto_shrink([false, false])
                        .show(ui, |ui| {
                            let editor_id = ui.make_persistent_id("fab_model_editor");
                            forget_foreign_history(ui.ctx(), editor_id, editor.owner, &editor.path);
                            let focused = ui.memory(|m| m.has_focus(editor_id));
                            // W.3.35: Tab / Shift+Tab re-indents the SELECTION. Intercept it BEFORE the
                            // widget — egui's default Tab moves focus (and `.code_editor()`'s would insert a
                            // lone `\t`), neither of which is what a code editor wants. `consume_key` pulls the
                            // event so focus stays put; we drive the pure transform + write the new selection
                            // back into the cursor state. Check SHIFT first — `consume_key` matches modifiers
                            // LOGICALLY (an extra Shift is ignored), so plain-Tab would otherwise eat Shift+Tab.
                            if focused {
                                let untab = ui.input_mut(|i| {
                                    i.consume_key(egui::Modifiers::SHIFT, egui::Key::Tab)
                                });
                                let tab = !untab
                                    && ui.input_mut(|i| {
                                        i.consume_key(egui::Modifiers::NONE, egui::Key::Tab)
                                    });
                                if (tab || untab)
                                    && let Some(mut st) =
                                        egui::text_edit::TextEditState::load(ui.ctx(), editor_id)
                                    && let Some(mut range) = st.cursor.char_range()
                                {
                                    let (a, b) = (range.primary.index.0, range.secondary.index.0);
                                    let (new_text, na, nb) =
                                        crate::editor_indent::reindent(&editor.text, a, b, untab);
                                    if new_text != editor.text {
                                        editor.text = new_text;
                                        editor.dirty = true;
                                        editor.edited_at = Some(time.elapsed_secs_f64());
                                    }
                                    range.primary.index = na.into();
                                    range.secondary.index = nb.into();
                                    st.cursor.set_char_range(Some(range));
                                    st.store(ui.ctx(), editor_id);
                                }
                            }
                            // W.3.38: the bracket pair to highlight — the (post-Tab) caret's adjacent bracket
                            // and its balanced partner, ONLY with an empty selection (a highlight while a
                            // range is selected is noise). Computed here so the layouter below captures it.
                            let bracket_hl = focused
                                .then(|| egui::text_edit::TextEditState::load(ui.ctx(), editor_id))
                                .flatten()
                                .and_then(|st| st.cursor.char_range())
                                .filter(|r| r.primary.index == r.secondary.index)
                                .and_then(|r| {
                                    let caret = crate::editor_indent::char_to_byte(
                                        &editor.text,
                                        r.primary.index.0,
                                    );
                                    crate::editor_brackets::match_bracket(&editor.text, caret)
                                });
                            // SCAD syntax highlighting (U.3.13): a layouter that lexes the buffer and paints
                            // each token by kind (fab-lang's own lexer → colors track the grammar), plus the
                            // W.3.38 bracket-match background.
                            let mut layouter =
                                |ui: &egui::Ui, buf: &dyn egui::TextBuffer, _w: f32| {
                                    let font = egui::TextStyle::Monospace.resolve(ui.style());
                                    let job = crate::highlight::scad_job(
                                        buf.as_str(),
                                        font,
                                        ui.visuals().text_color(),
                                        bracket_hl,
                                    );
                                    ui.fonts_mut(|f| f.layout_job(job))
                                };
                            // `ui.add` (NOT `add_sized`): add_sized centres/justifies its child, which
                            // scrolls a long line to its MIDDLE on open — a code editor must sit at
                            // column 0 and scroll right from there. `desired_rows` fills the panel
                            // height so a short file doesn't leave it half-empty (what add_sized gave).
                            let row_h = ui.text_style_height(&egui::TextStyle::Monospace);
                            let rows = (ui.available_height() / row_h).floor().max(1.0) as usize;
                            // W.3.39: a line-number gutter so a W.3.37 "line N" error is findable. Right-
                            // justified muted monospace (same TextStyle::Monospace as the editor → identical
                            // row height, no drift), non-selectable; the 2px top space matches the TextEdit's
                            // default vertical margin so line 1 aligns. It rides inside the same both()-scroll,
                            // so a long line scrolls it horizontally too — fine for SCAD's short lines.
                            let line_count =
                                editor.text.bytes().filter(|&b| b == b'\n').count() + 1;
                            let digits = line_count.to_string().len();
                            let nums = (1..=line_count).fold(
                                String::with_capacity(line_count * (digits + 1)),
                                |mut s, n| {
                                    if n > 1 {
                                        s.push('\n');
                                    }
                                    use std::fmt::Write;
                                    let _ = write!(s, "{n:>digits$}");
                                    s
                                },
                            );
                            let resp = ui
                                .horizontal_top(|ui| {
                                    ui.vertical(|ui| {
                                        ui.add_space(2.0);
                                        ui.add(
                                            egui::Label::new(
                                                egui::RichText::new(nums)
                                                    .monospace()
                                                    .color(theme::TEXT_MUTED),
                                            )
                                            .selectable(false),
                                        );
                                    });
                                    ui.add(
                                        egui::TextEdit::multiline(&mut editor.text)
                                            .id(editor_id)
                                            .code_editor()
                                            .desired_width(f32::INFINITY)
                                            .desired_rows(rows)
                                            .layouter(&mut layouter),
                                    )
                                })
                                .inner;
                            if resp.changed() {
                                editor.dirty = true;
                                editor.edited_at = Some(time.elapsed_secs_f64());
                            }
                        });
                }
                Tab::Customize => {
                    // Params → widgets → source-splice back into the buffer (X.2); the debounced
                    // preview re-render (shared with the editor) does the rest.
                    crate::customize::customize_panel(
                        ui,
                        &cv_params,
                        &mut editor,
                        time.elapsed_secs_f64(),
                        cv_defaults,
                    );
                }
                Tab::Parts => {
                    // Printer bed (W.3.8): the build volume every part slices + packs against — a
                    // per-MODEL slicing input (not a global), so it lives on the Parts tab and persists
                    // in the .scad's fab:config on Save. That's the web's only bed source (no
                    // printers.toml in the browser), so a `?model=` reload sizes right. Edit a COPY so
                    // DragValue's mutable borrow can't false-trip SceneCfg's change detection — only a
                    // REAL delta writes back (→ `resize_bed` reshapes the slab + re-arms auto-plan).
                    {
                        let mut bed = scene.bed;
                        ui.horizontal(|ui| {
                            ui.label(theme::chrome("printer bed", 15.0).color(theme::NAVY));
                            for (axis, i) in [("X", 0usize), ("Y", 1), ("Z", 2)] {
                                ui.label(egui::RichText::new(axis).small().weak());
                                ui.add(
                                    egui::DragValue::new(&mut bed[i])
                                        .speed(1.0)
                                        .range(10.0..=1000.0)
                                        .fixed_decimals(0)
                                        .suffix(" mm"),
                                );
                            }
                        });
                        if bed != scene.bed {
                            // Slaves the export plate to the new bed. Unsaved via the config
                            // fingerprint (TG.1) — no `editor.dirty` patch for a file switch to erase.
                            scene.set_configured_bed(bed);
                        }
                    }
                    ui.separator();
                    // THE DRILL (U.3.3): part → cut → connector, top to bottom. A collapsing section
                    // per top-level part (green + bold = active); its body flattens to that part's
                    // cuts; expanding a cut (▼) reveals its connectors inline. The active part drives
                    // the slice systems + cut-plane overlays, so an edit reslices the right part.
                    ui.label(
                        egui::RichText::new("parts · cuts · connectors")
                            .small()
                            .weak(),
                    );
                    let n = parts.0.len();
                    let mut autoplace_req = false;
                    for i in 0..n {
                        let is_active = active_part.0 == i;
                        // max with the part's component count so a PRESLICED part (0 cuts, N disjoint
                        // pieces) reads "N pcs", not "1 pc" — piece_estimate alone ignores components.
                        let pcs = piece_estimate(&parts.0[i].cuts).max(parts.0[i].pieces);
                        let label = format!(
                            "{} · {} pc{}",
                            part_label(&parts.0[i].name, i),
                            pcs,
                            if pcs == 1 { "" } else { "s" }
                        );
                        // Oswald caps header (chrome). Active cue = a painted gold left-rule +
                        // default-open; NO green, NO fake-bold (Oswald is 400 only).
                        let header = theme::chrome(&label, 15.0).color(theme::NAVY);
                        let mut select = false;
                        let resp = egui::CollapsingHeader::new(header)
                            .id_salt(("part", i))
                            .default_open(is_active)
                            .show(ui, |ui| {
                                select |= part_cut_editor(
                                    ui,
                                    &mut parts.0[i],
                                    i,
                                    is_active,
                                    &mut edit,
                                    &mut active,
                                    &mut to_remove,
                                    &mut autoplace_req,
                                );
                            });
                        if is_active {
                            // gold left-rule marks the active part (matches the active-cut rule)
                            let r = resp.header_response.rect;
                            ui.painter().vline(
                                r.left(),
                                r.y_range(),
                                egui::Stroke::new(2.0, theme::GOLD),
                            );
                        }
                        if select || resp.header_response.clicked() {
                            active_part.0 = i;
                            parts.set_changed(); // a pure selection must refresh the active-part visuals
                        }
                    }
                    // An Auto-place click inside the drill bubbles up here (the writer can't cross the
                    // part-borrow into `part_cut_editor`).
                    if autoplace_req {
                        writers.autoplace.write(AutoPlace);
                    }
                    ui.separator();
                    // Slicing itself is reactive (background reslice on cut changes) — these are the
                    // only two Parts actions, and each ALWAYS has an effect: no dead buttons (U.3.15).
                    let (has_cuts, spread) = {
                        let p = &parts.0[active_part.0];
                        (p.cuts.list.iter().any(|c| c.enabled), p.spread)
                    };
                    // Reset-to-auto: throw away this part's cuts+connectors and re-derive the full plan
                    // (fit-to-bed cuts + auto-placed connectors, or WHOLE if it fits).
                    if ui
                        .button(format!("{}  Reset to auto", icons::RESTART))
                        .clicked()
                    {
                        writers.cmd.write(PanelCmd::AutoSlice);
                    }
                    // Explode is a per-part VIEW toggle, enabled only when the part has pieces to fan —
                    // a part that fits the bed is whole, so there's nothing to explode.
                    if ui
                        .add_enabled(
                            has_cuts,
                            egui::Button::new(if spread > 0.0 { "Assemble" } else { "Explode" }),
                        )
                        .clicked()
                    {
                        writers.cmd.write(PanelCmd::ToggleView);
                    }
                    // Slice summary (mockup's eg-status): part count + estimated piece total (each
                    // part's cut estimate, floored by its presliced component count — see the header).
                    let total: usize = parts
                        .0
                        .iter()
                        .map(|p| piece_estimate(&p.cuts).max(p.pieces))
                        .sum();
                    ui.label(
                        egui::RichText::new(format!(
                            "{n} part{} · {total} pieces",
                            if n == 1 { "" } else { "s" }
                        ))
                        .small()
                        .weak(),
                    );
                }
                Tab::Orientation => {
                    ui.label(egui::RichText::new("print orientation").small().weak());
                    ui.label(
                        egui::RichText::new(
                            "click a piece in the view to set which face prints down",
                        )
                        .small()
                        .weak(),
                    );
                    ui.separator();
                    // Every printable piece across ALL parts (co-pack), each flagged flat (a manual
                    // orientation set) vs auto (still the least-support auto-pick). The mode + 3D
                    // click-to-orient already run while this tab is up; this is the readout + per-piece
                    // reset. `PrintPieces` is None until the first slice lands.
                    match view.print_pieces.0.as_ref() {
                        None => {
                            ui.label(
                                egui::RichText::new("slice a part first — no pieces yet")
                                    .small()
                                    .weak(),
                            );
                        }
                        Some(pieces) => {
                            let mut flat = 0usize;
                            let mut nth: std::collections::HashMap<usize, usize> =
                                std::collections::HashMap::new();
                            for (part, pp) in pieces {
                                let Some(p) = parts.0.get(*part) else {
                                    continue;
                                };
                                let key = (pp.piece, pp.comp);
                                let manual = p.orient.manual.contains(&key);
                                if manual {
                                    flat += 1;
                                }
                                let n = {
                                    let c = nth.entry(*part).or_insert(0);
                                    *c += 1;
                                    *c
                                };
                                let label = format!("{} · pc {}", part_label(&p.name, *part), n);
                                ui.horizontal(|ui| {
                                    ui.label(label);
                                    ui.with_layout(
                                        egui::Layout::right_to_left(egui::Align::Center),
                                        |ui| {
                                            if manual {
                                                // manual → seated flat; a click resets it to the auto-pick.
                                                if ui
                                                    .small_button(icons::RESTART)
                                                    .on_hover_text("reset to auto")
                                                    .clicked()
                                                {
                                                    reset_orient = Some((*part, key));
                                                }
                                                ui.label(
                                                    egui::RichText::new(format!(
                                                        "flat {}",
                                                        icons::CHECK
                                                    ))
                                                    .monospace()
                                                    .color(theme::NAVY)
                                                    .strong(),
                                                );
                                            } else {
                                                ui.label(
                                                    egui::RichText::new("auto")
                                                        .monospace()
                                                        .color(theme::GOLD_DIM),
                                                );
                                            }
                                        },
                                    );
                                });
                            }
                            ui.separator();
                            ui.label(
                                egui::RichText::new(format!(
                                    "{} pieces · {} seated flat",
                                    pieces.len(),
                                    flat
                                ))
                                .small()
                                .weak(),
                            );
                        }
                    }
                }
                Tab::Export => {
                    // The co-pack preview metric (U.3.5): `estimate_copack` keeps this live as pieces +
                    // orientations change — no button to compute it. Then the two output actions.
                    ui.label(egui::RichText::new("co-packed plates").small().weak());
                    match &view.copack.summary {
                        Some(s) => {
                            ui.label(
                                egui::RichText::new(format!(
                                    "{} plates · {} pieces · fits {:.0}×{:.0}",
                                    s.plates, s.pieces, view.copack.bed[0], view.copack.bed[1]
                                ))
                                .strong(),
                            );
                            ui.label(
                                egui::RichText::new(format!(
                                    "{}% full",
                                    (s.fill * 100.0).round() as i32
                                ))
                                .small()
                                .weak(),
                            );
                        }
                        None => {
                            ui.label(
                                egui::RichText::new("slice a part first — nothing to pack yet")
                                    .small()
                                    .weak(),
                            );
                        }
                    }
                    ui.separator();
                    // CTA buttons: gold fill + navy Oswald caption (the site's accent button).
                    if ui
                        .add(
                            egui::Button::new(
                                theme::chrome("Export plates (3MF)", 14.0).color(theme::NAVY),
                            )
                            .fill(theme::GOLD),
                        )
                        .clicked()
                    {
                        writers.cmd.write(PanelCmd::Export);
                    }
                    // Desktop: publish a NEW hotchkiss.io gallery item (shells OpenSCAD + native HTTP).
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        if ui
                            .add(
                                egui::Button::new(
                                    theme::chrome("Publish -> hotchkiss.io", 14.0)
                                        .color(theme::NAVY),
                                )
                                .fill(theme::GOLD),
                            )
                            .clicked()
                        {
                            writers.cmd.write(PanelCmd::Publish);
                        }
                    }
                    // Web (W.3.29.4): publish a NEW /3d gallery item from the browser (fetch + session
                    // cookie, no OpenSCAD) — the dialog names it, admin-only server-side (loud on 401/403).
                    // The parity of the desktop Publish; distinct from the save-back Update below.
                    #[cfg(target_arch = "wasm32")]
                    {
                        if ui
                            .add(
                                egui::Button::new(
                                    theme::chrome("Publish -> hotchkiss.io", 14.0)
                                        .color(theme::NAVY),
                                )
                                .fill(theme::GOLD),
                            )
                            .on_hover_text("create a NEW /3d gallery item (admin only)")
                            .clicked()
                        {
                            writers.cmd.write(PanelCmd::Publish);
                        }
                    }
                    // Web (W.3.18): push the finished result back to the item it came from — the save-back
                    // (source + mesh variants + the printable plate, since the pieces live on this tab).
                    // Only when opened from a media item (save_target set); this UPDATES in place, distinct
                    // from the Publish button above which mints a new item.
                    #[cfg(target_arch = "wasm32")]
                    {
                        if view.save_target.0.is_some()
                            && ui
                                .add(
                                    egui::Button::new(
                                        theme::chrome("Update -> hotchkiss.io", 14.0)
                                            .color(theme::NAVY),
                                    )
                                    .fill(theme::GOLD),
                                )
                                .on_hover_text(
                                    "update this model's files on hotchkiss.io (meshes + plate)",
                                )
                                .clicked()
                        {
                            writers.cmd.write(PanelCmd::SaveToSite);
                        }
                    }
                }
            }
            // Fill the panel to full height on every tab so its frame reaches the status bar (U.3.2).
            ui.add_space(ui.available_height());
        });
    if let Some((p, idx)) = to_remove
        && let Some(part) = parts.0.get_mut(p)
    {
        remove_cut(&mut part.cuts, &mut part.conns, idx);
    }
    if let Some((part, key)) = reset_orient {
        if let Some(p) = parts.0.get_mut(part) {
            p.orient.reset(key);
        }
        parts.set_changed(); // re-seat this piece at the auto-pick (sync_orientation guards on is_changed)
    }
    seam.width_px = panel.response.rect.width() * ctx.pixels_per_point();
    seam.top_px = top.response.rect.height() * ctx.pixels_per_point();
    seam.bottom_px = bottom.response.rect.height() * ctx.pixels_per_point();
    seam.over_ui = ctx.egui_wants_pointer_input() || ctx.is_pointer_over_egui();
}

/// Render one part's cut + connector drill — the middle and inner levels of the part → cut →
/// connector tree (U.3.3). Each cut is a flat stack-order row whose `▸/▼` triangle expands its
/// connectors inline (and drives the 2D face-on cross-section editor through `edit`); a trailing
/// `+X/+Y/+Z` strip adds a plane. Returns `true` if the user TOUCHED anything, so the caller makes
/// this part active and the reactive slice follows the edit. `part_idx` tags a deferred delete with
/// its owner; `autoplace_req` bubbles an Auto-place click up to the caller's message writer (which
/// can't cross the `part` borrow).
#[allow(
    clippy::too_many_arguments,
    reason = "the drill threads one part plus edit/active/remove/autoplace channels; a bundle struct just relocates the arity, not the noise"
)]
pub(crate) fn part_cut_editor(
    ui: &mut egui::Ui,
    part: &mut Part,
    part_idx: usize,
    is_active_part: bool,
    edit: &mut EditCut,
    active: &mut ActiveConn,
    to_remove: &mut Option<(usize, usize)>,
    autoplace_req: &mut bool,
) -> bool {
    let mut touched = false;
    // CUTS — a flat stack-order list (the connector `.cut` field indexes THIS order, so don't
    // reorder). Only the active part edits connectors, so its `▼` state gates the inline drill.
    let n = part.cuts.list.len();
    for idx in 0..n {
        let axis = part.cuts.list[idx].axis;
        let editing = is_active_part && edit.0 == Some(idx);
        let is_cut_active = idx == part.cuts.active;
        let cut_row = ui.horizontal(|ui| {
            // Expand this cut's connectors (and enter the 2D face-on editor — both ride `edit`). A real
            // Material Symbols glyph from the build.rs-managed icon font: chevron_right when collapsed,
            // expand_more when open (U.2.1). Frameless clickable label = a bare chevron, per the mockup.
            let glyph = if editing {
                icons::EXPAND_MORE
            } else {
                icons::CHEVRON_RIGHT
            };
            if ui
                .add(egui::Label::new(glyph).sense(egui::Sense::click()))
                .clicked()
            {
                edit.0 = if editing { None } else { Some(idx) };
                part.cuts.active = idx;
                touched = true;
            }
            let name = format!("{} cut @", axis.label());
            // Active row = navy + weight (a readout, not chrome — stays mixed-case Ubuntu-Light); the
            // gold accent is the painted left-rule below, matching the active-part header.
            ui.label(if is_cut_active {
                egui::RichText::new(name).color(theme::NAVY).strong()
            } else {
                egui::RichText::new(name)
            });
            let mut at = part.cuts.list[idx].at;
            if ui.add(egui::DragValue::new(&mut at).speed(0.5)).changed() {
                part.cuts.list[idx].at = clamp_to_bounds(at, axis, &part.bounds);
                part.cuts.active = idx;
                touched = true;
            }
            let en = part.cuts.list[idx].enabled;
            // Eye / eye-off = the cut's in/out of the slice (U.2 icon swap; hover names it).
            if ui
                .selectable_label(en, if en { icons::EYE } else { icons::EYE_OFF })
                .on_hover_text(if en { "in the slice" } else { "disabled" })
                .clicked()
            {
                part.cuts.list[idx].enabled = !en;
                touched = true;
            }
            if ui
                .button(egui::RichText::new(icons::DELETE).color(theme::DANGER))
                .on_hover_text("delete cut")
                .clicked()
            {
                *to_remove = Some((part_idx, idx));
                touched = true;
            }
        });
        if is_cut_active {
            // gold left-rule marks the active cut (matches the active-part header rule)
            ui.painter().vline(
                cut_row.response.rect.left(),
                cut_row.response.rect.y_range(),
                egui::Stroke::new(2.0, theme::GOLD),
            );
        }
        // CONNECTORS — inline under the expanded cut (the old Connectors mode, now nested). Sets the
        // active connector TYPE + does auto-place / clear for THIS cut; click-to-place lives in the
        // 2D editor on the same `edit` state.
        if editing {
            ui.indent(("conn", idx), |ui| {
                ui.label(egui::RichText::new("connectors — this cut").small().weak());
                ui.horizontal(|ui| {
                    if ui
                        .selectable_label(active.kind == fab::ConnKind::Onion, "Onion")
                        .clicked()
                    {
                        active.kind = fab::ConnKind::Onion;
                    }
                    if ui
                        .selectable_label(active.kind == fab::ConnKind::Bolt, "Bolt")
                        .clicked()
                    {
                        active.kind = fab::ConnKind::Bolt;
                    }
                });
                if active.kind == fab::ConnKind::Bolt {
                    ui.horizontal(|ui| {
                        for s in [Screw::M3, Screw::M4, Screw::M5] {
                            if ui.selectable_label(active.screw == s, s.label()).clicked() {
                                active.screw = s;
                            }
                        }
                    });
                }
                ui.horizontal(|ui| {
                    if ui.button("Auto-place").clicked() {
                        *autoplace_req = true;
                    }
                    if ui.button("Clear").clicked() {
                        part.conns.list.retain(|c| c.cut != idx);
                    }
                });
            });
        }
    }
    // ADD PLANES — one combined +X/+Y/+Z strip (replaces the old per-axis "+" sections), matching
    // the v4 mockup. A new plane drops at the part's mid-span on that axis.
    ui.horizontal(|ui| {
        for axis in [Axis::X, Axis::Y, Axis::Z] {
            if ui
                .button(format!("{} {}", icons::ADD, axis.label()))
                .clicked()
                && let Some((mn, mx)) = part.bounds.0
            {
                let at = comp((mn + mx) * 0.5, axis.index());
                part.cuts.list.push(CutDef {
                    axis,
                    at,
                    enabled: true,
                });
                part.cuts.active = part.cuts.list.len() - 1;
                touched = true;
            }
        }
    });
    touched
}

/// The accordion label for part `i`: its provenance name (the top-level module/function that made
/// it) capped to a stable width + an ordinal suffix — `wall_sliced·1`, `frame·2` — or a generic
/// `Part N` when the part is anonymous (a bare block / an ambiguous split). The suffix keeps labels
/// short + uniform and disambiguates two parts from the SAME module (T.2b).
pub(crate) fn part_label(name: &Option<String>, i: usize) -> String {
    const CAP: usize = 12; // chars, before the ·ordinal — keeps the accordion column tidy
    match name {
        Some(n) if n.chars().count() > CAP => {
            let short: String = n.chars().take(CAP - 1).collect();
            format!("{short}…·{}", i + 1)
        }
        Some(n) => format!("{n}·{}", i + 1),
        None => format!("Part {}", i + 1),
    }
}

/// A rough printable-piece count for a part's cut stack — the product over axes of (enabled cuts on
/// that axis + 1). Ignores connected-components (a presliced blob reads as 1 until sliced), so it's
/// a fast accordion label, not the exact plate count.
pub(crate) fn piece_estimate(cuts: &Cuts) -> usize {
    [Axis::X, Axis::Y, Axis::Z]
        .iter()
        .map(|&ax| {
            cuts.list
                .iter()
                .filter(|c| c.enabled && c.axis == ax)
                .count()
                + 1
        })
        .product()
}

/// Fire `fab-gui:ready` — a `document` CustomEvent — ONCE, when the first themed egui frame is up: the
/// host page's cue to remove its boot splash (docs/web-embed.md). Runs right after `panel_ui` in the
/// egui pass, so by the time it fires the tool UI has been submitted for the frame. No-op on desktop —
/// there's no host page to tell. The `Local` latches it to a single dispatch for the app's lifetime.
pub(crate) fn signal_ready(mut fired: Local<bool>, mut contexts: EguiContexts) {
    if *fired || contexts.ctx_mut().is_err() {
        return; // egui context not up yet — wait for a real painted frame
    }
    *fired = true;
    #[cfg(target_arch = "wasm32")]
    if let Some(doc) = web_sys::window().and_then(|w| w.document())
        && let Ok(ev) = web_sys::CustomEvent::new("fab-gui:ready")
    {
        let _ = doc.dispatch_event(&ev);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn charged(prog: f32) -> Hold {
        Hold {
            prog,
            latched: false,
        }
    }

    /// One frame of a lone code editor at `id`, focused, fed `events`; `held` names whose buffer it is
    /// the way `panel_ui` does (`None` = no reset, the pre-fix widget).
    fn editor_frame(
        ctx: &egui::Context,
        id: egui::Id,
        t: f64,
        text: &mut String,
        events: Vec<egui::Event>,
        held: Option<(Option<crate::project::DocId>, &std::path::Path)>,
    ) {
        let input = egui::RawInput {
            time: Some(t),
            events,
            ..Default::default()
        };
        let _ = ctx.run_ui(input, |ui| {
            if let Some((owner, path)) = held {
                forget_foreign_history(ui.ctx(), id, owner, path);
            }
            ui.memory_mut(|m| m.request_focus(id));
            ui.add(egui::TextEdit::multiline(text).id(id).code_editor());
        });
    }

    fn cmd_z() -> Vec<egui::Event> {
        vec![egui::Event::Key {
            key: egui::Key::Z,
            physical_key: None,
            pressed: true,
            repeat: false,
            modifiers: egui::Modifiers::COMMAND,
        }]
    }

    /// TG.2 (spec: nothing in an opened document comes from the previous one's editor): Cmd+Z right
    /// after the buffer changes hands must not restore the previous file's text. egui's undoer keeps
    /// whole-text snapshots under the widget id, and the first half shows it really does leak without
    /// the reset, so this can't pass vacuously. Within one file, undo still works.
    #[test]
    fn undo_never_crosses_into_the_previous_documents_text() {
        let id = egui::Id::new("fab_model_editor");
        let path = std::path::Path::new("/tmp/fab-gui/scadproj/brace/main.scad");
        let (a, b) = (
            crate::project::ProjectDoc::default().id(),
            crate::project::ProjectDoc::default().id(),
        );
        // Each run: A's text is on screen and focused, then a same-path document B is adopted (only
        // the buffer and its owner change, as `adopt` does), then Cmd+Z.
        let run = |reset: bool| {
            let ctx = egui::Context::default();
            let mut text = "cube(1);".to_string();
            for t in 0..3 {
                editor_frame(
                    &ctx,
                    id,
                    t as f64,
                    &mut text,
                    vec![],
                    reset.then_some((Some(a), path)),
                );
            }
            text = "sphere(2);".to_string();
            editor_frame(
                &ctx,
                id,
                3.0,
                &mut text,
                cmd_z(),
                reset.then_some((Some(b), path)),
            );
            text
        };
        assert_eq!(
            run(false),
            "cube(1);",
            "without the reset egui leaks A's text into B"
        );
        assert_eq!(run(true), "sphere(2);", "B's text stays B's");

        // The same owner and file keep their history: an edit undoes back to the loaded text.
        let ctx = egui::Context::default();
        let mut text = "cube(1);".to_string();
        let held = Some((Some(a), path));
        for t in 0..3 {
            editor_frame(&ctx, id, t as f64, &mut text, vec![], held);
        }
        text.push_str(" // edit");
        editor_frame(&ctx, id, 3.0, &mut text, cmd_z(), held);
        assert_eq!(text, "cube(1);");
    }

    /// TG.2: the hold's charge — fills over HOLD_SECS, fires exactly once at full, drains twice as
    /// fast on release, and never leaves 0..=1.
    #[test]
    fn hold_fills_fires_once_and_drains() {
        let frame = HOLD_SECS / 4.0;
        let mut h = Hold::default();
        for _ in 0..3 {
            let fired;
            (h, fired) = h.step(frame, true);
            assert!(!fired, "fired early at {}", h.prog);
        }
        assert!(
            (h.prog - 0.75).abs() < 1e-5,
            "three quarter-holds = 0.75, got {}",
            h.prog
        );
        let fired;
        (h, fired) = h.step(frame, true);
        assert!(fired, "a full hold fires");
        assert_eq!(h.prog, 0.0, "and shows empty");

        // Release: drains at twice the fill rate, floors at empty, never fires.
        let (q, fired) = charged(0.75).step(frame, false);
        assert!(!fired);
        assert!(
            (q.prog - 0.25).abs() < 1e-5,
            "a quarter-hold of release drains 0.5, got {}",
            q.prog
        );
        assert_eq!(q.step(frame, false), (Hold::default(), false));
        // A click (one short press, then release) never fires.
        let (q, fired) = Hold::default().step(1.0 / 60.0, true);
        assert!(!fired && q.prog < 1.0);
        // A huge frame (a stall) clamps rather than overshooting.
        assert!(Hold::default().step(10.0, true).1);
        assert_eq!(charged(0.5).step(10.0, false), (Hold::default(), false));
    }

    fn vals(width: &str) -> Defaults {
        Defaults::from([("width".to_string(), width.to_string())])
    }

    /// TG.2 review: the Customize defaults never cross documents. Two same-stem archives share one
    /// temp entry path, and a re-open reproduces its own path — either used to keep the OLD document's
    /// as-loaded values, so a freshly opened, clean document offered Reset and spliced them in.
    #[test]
    fn customize_defaults_recapture_for_a_new_document_at_the_same_path() {
        let entry = std::path::Path::new("/tmp/fab-gui/scadproj/brace/main.scad");
        let (a, b) = (
            crate::project::DocId::default(),
            crate::project::DocId::default(),
        );
        let mut d = CustDefaults::default();
        assert_eq!(d.capture(Some(a), entry, || vals("10")), &vals("10"));
        // Same document, later frame: the capture sticks (the buffer may be customized by now).
        assert_eq!(d.capture(Some(a), entry, || vals("20")), &vals("10"));
        // Same path, NEW document (same-stem archive, or a re-open of a saved file): recaptured.
        assert_eq!(d.capture(Some(b), entry, || vals("30")), &vals("30"));
        // A rename within the document moves the capture with the file.
        let moved = std::path::PathBuf::from("/tmp/fab-gui/scadproj/brace/brace.scad");
        d.rename(entry, moved.clone());
        assert_eq!(d.capture(Some(b), &moved, || vals("99")), &vals("30"));
    }

    /// TG.2 review: a hold kept down past the fire must NOT recharge and fire again. The row delete
    /// keys its hold by row index, so a second fire after the list shifts would delete the next file.
    /// Only a release re-arms it.
    #[test]
    fn a_continued_hold_never_fires_twice() {
        let frame = HOLD_SECS / 4.0;
        let (mut h, fired) = charged(0.9).step(frame, true);
        assert!(fired);
        for _ in 0..40 {
            let again;
            (h, again) = h.step(frame, true);
            assert!(!again, "a held-down button refired");
            assert_eq!(h.prog, 0.0, "a latched hold shows no charge");
        }
        // Release, then a fresh full hold fires again.
        (h, _) = h.step(frame, false);
        assert_eq!(h, Hold::default(), "a release re-arms");
        let mut fires = 0;
        for _ in 0..4 {
            let f;
            (h, f) = h.step(frame, true);
            fires += f as u32;
        }
        assert_eq!(fires, 1);
    }
}
