//! The egui control panel (the only egui UI outside the mode builders).

use crate::*;

/// Material Symbols glyph codepoints — GENERATED by `build.rs` from the font manifest (U.2.1), so the
/// glyphs the panel draws are exactly the ones subset into `MaterialSymbols-subset.ttf`. Do not edit.
#[allow(dead_code)] // ADD/DELETE/EYE/… are wired as button icons in U.2; generated as one set.
mod icons {
    include!(concat!(env!("OUT_DIR"), "/icon_glyphs.rs"));
}

/// The panel's outbound message writers, bundled so `panel_ui` spends ONE system param on all
/// three (Bevy caps a system at 16 params).
#[derive(SystemParam)]
pub(crate) struct PanelWriters<'w> {
    pub(crate) switch: MessageWriter<'w, SwitchFile>,
    pub(crate) autoplace: MessageWriter<'w, AutoPlace>,
    pub(crate) cmd: MessageWriter<'w, PanelCmd>,
    /// W.3.16 console UI state — folded in here (not a separate `panel_ui` param) to stay under Bevy's
    /// 16-param cap. The console CONTENT lives in a global buffer (`crate::console`), not the ECS.
    pub(crate) console: ResMut<'w, crate::console::ConsoleUi>,
}

/// The read-only display inputs the tabs render, bundled so `panel_ui` stays under Bevy's 16-param cap
/// (U.3). Grew as the Orientation/Export tabs (`print_pieces`, `copack`), the platform gate
/// (`platform`), and the pipeline feedback (`pipeline`) landed.
#[derive(SystemParam)]
pub(crate) struct PanelView<'w> {
    pub(crate) print_pieces: Res<'w, PrintPieces>,
    pub(crate) copack: Res<'w, CoPack>,
    pub(crate) platform: Res<'w, Platform>,
    pub(crate) pipeline: Res<'w, Pipeline>,
    /// The save-back target (W.5.7): `Some` ⇒ show the "Save to hotchkiss.io" affordance.
    pub(crate) save_target: Res<'w, SaveTarget>,
}

/// The whole control panel (U.3), immediate-mode: an app-wide top tab bar + bottom status bar +
/// a left egui panel whose contents route on the active `Tab` (Model / Parts / Orientation / Export).
/// Cheap edits mutate in place; a heavy action (needing params beyond the panel's own) writes a
/// `PanelCmd` its dedicated system handles. Writes `PanelSeam` after drawing so `orbit` yields the
/// pointer over the panels and `split_viewport` insets the 3D camera inside all three bars.
#[allow(clippy::too_many_arguments)]
// On wasm the desktop-only file picker is gated out, so `open_dialog` is read but never written there.
#[cfg_attr(target_arch = "wasm32", allow(unused_mut))]
pub(crate) fn panel_ui(
    mut contexts: EguiContexts,
    mut parts: ResMut<Parts>,
    mut active_part: ResMut<ActivePart>,
    mut active: ResMut<ActiveConn>,
    mut edit: ResMut<EditCut>,
    mut tab: ResMut<Tab>,
    files: Res<FileList>,
    status: Res<Status>,
    mut open_dialog: ResMut<OpenDialog>,
    mut editor: ResMut<EditorBuf>,
    mut scene: ResMut<SceneCfg>,
    time: Res<Time>,
    view: PanelView,
    mut writers: PanelWriters,
    mut seam: ResMut<PanelSeam>,
    // X.2.4 reset-to-default: per-file map of param name → as-loaded value. A `Local` (not a resource)
    // so it needs no per-app init and captures automatically in every app that runs `panel_ui`.
    mut cust_defaults: Local<
        std::collections::HashMap<std::path::PathBuf, std::collections::HashMap<String, String>>,
    >,
) {
    let Ok(ctx) = contexts.ctx_mut() else {
        return;
    };
    // X.2: the customizer params for the current buffer (owned, so it doesn't hold `editor`'s borrow).
    // Drives the conditional Customize tab + its widgets. Cheap — `customize` parses only the buffer.
    let cv_params = crate::customize::extract(&editor.text);
    // Capture the as-loaded defaults the first time we see this file (first frame ⇒ still the file's own
    // values, before any customization). Keyed by path, so a file switch captures fresh defaults.
    cust_defaults.entry(editor.path.clone()).or_insert_with(|| {
        cv_params
            .iter()
            .map(|p| {
                let v = editor
                    .text
                    .get(p.value_span.clone())
                    .unwrap_or("")
                    .trim()
                    .to_string();
                (p.name.clone(), v)
            })
            .collect()
    });
    let cv_defaults = cust_defaults.get(&editor.path);
    // A delete defers past the row loop (index stability), tagged with the PART it belongs to (T.2b).
    let mut to_remove: Option<(usize, usize)> = None;
    // A per-piece "reset to auto" (U.3.4) likewise defers past the Orientation list's `parts` borrow.
    let mut reset_orient: Option<(usize, PieceKey)> = None;
    // egui 0.35 panels show INTO a Ui, not the Context — wrap the viewport in a background-layer Ui
    // first (the bevy_egui side_panel pattern) so the panels overlay the 3D view.
    let mut viewport = egui::Ui::new(
        ctx.clone(),
        egui::Id::new("panel_viewport"),
        egui::UiBuilder::new()
            .layer_id(egui::LayerId::background())
            .max_rect(ctx.viewport_rect()),
    );
    // Heavy navy-bordered div-grey card, 8px pad — the site's chrome surface. Every bar/panel uses it.
    let panel_frame = || {
        egui::Frame::new()
            .fill(theme::DIV_GREY)
            .stroke(egui::Stroke::new(2.0, theme::NAVY))
            .inner_margin(egui::Margin::same(8))
    };
    // TOP BAR (U.3): the workflow tabs — Model → Parts → Orientation → Export. Each is a navy pill (the
    // site's nav); the ACTIVE one is gold-lettered with a gold underline (the retired green is gone).
    let top = egui::Panel::top("topbar")
        .frame(panel_frame())
        .show(&mut viewport, |ui| {
            ui.horizontal(|ui| {
                ui.label(theme::chrome("fab-gui", 22.0).color(theme::NAVY));
                // the site's serif voice — a Quattrocento tagline beside the wordmark
                ui.label(
                    egui::RichText::new("slice · orient · pack")
                        .font(theme::quattro(13.0))
                        .color(theme::TEXT_MUTED),
                );
                ui.separator();
                // The Customize tab (X.2) slots in after Model, but ONLY when the model exposes
                // parameters — an empty customizer is a wart, so the tab appears with the content.
                let mut bar: Vec<(Tab, &'static str)> = Vec::with_capacity(5);
                for (t, label) in Tab::ALL {
                    bar.push((t, label));
                    if t == Tab::Model && !cv_params.is_empty() {
                        bar.push((Tab::Customize, "Customize"));
                    }
                }
                for (t, label) in bar {
                    let on = *tab == t;
                    let caption = theme::chrome(label, 15.0).color(if on {
                        theme::GOLD
                    } else {
                        theme::DIV_GREY
                    });
                    let resp = ui.add(egui::Button::new(caption).fill(theme::NAVY));
                    if on {
                        // the site's signature: a gold underline on the active tab
                        ui.painter().hline(
                            resp.rect.x_range(),
                            resp.rect.bottom() - 1.0,
                            egui::Stroke::new(2.0, theme::GOLD),
                        );
                    }
                    if resp.clicked() {
                        *tab = t;
                    }
                    // Per-node feedback (U.3.7): a gold spinner while THIS stage computes (fires on the
                    // first render too), else a GOLD_DIM stale dot when its output is behind its input.
                    if view.pipeline.loading[t.index()] {
                        ui.add(egui::Spinner::new().size(12.0).color(theme::GOLD));
                    } else if view.pipeline.dirty[t.index()] {
                        // icons::DOT (Material Symbols), NOT a raw bullet — the font stack would tofu it.
                        ui.colored_label(theme::GOLD_DIM, icons::DOT);
                    }
                }
            });
        });
    // BOTTOM BAR (U.3): the status line — a gold spinner + navy activity label while a job runs (the
    // pipeline's ACCURATE activity, never the possibly-stale imperative `Status`); the imperative
    // status shows only when idle (the last result / error / "ready").
    // W.3.16: the status bar expands into a CONSOLE. Collapsed = one status row; expanded = a resizable
    // panel with the echo/warnings (+ optional tracing) below. Size decided from last frame's state so
    // the panel height and its content agree (a fresh toggle lands next frame — imperceptible).
    let console_expanded = writers.console.expanded;
    let mut statusbar = egui::Panel::bottom("statusbar").frame(panel_frame());
    if console_expanded {
        statusbar = statusbar
            .resizable(true)
            .default_size(220.0)
            .min_size(96.0)
            .max_size(480.0);
    }
    let bottom = statusbar.show(&mut viewport, |ui| {
        // Status ROW: the pipeline's accurate activity while busy (never the possibly-stale imperative
        // Status), else the imperative status — with the console controls right-aligned.
        ui.horizontal(|ui| {
            match &view.pipeline.activity {
                Some(activity) if view.pipeline.busy => {
                    ui.add(egui::Spinner::new().size(14.0).color(theme::GOLD));
                    ui.colored_label(theme::NAVY, activity.as_str());
                    ui.ctx().request_repaint();
                }
                _ => {
                    ui.label(status.0.as_str());
                }
            }
            ui.separator();
            // W.3.25.2: live-view quality — Draft (fast) / Final (see the real smoothness). Session-only;
            // export always renders Final. Flipping it re-renders the buffer (bumps edited_at).
            let mut want_final = crate::render_quality::is_final();
            let before = want_final;
            ui.selectable_value(&mut want_final, false, "Draft");
            ui.selectable_value(&mut want_final, true, "Final");
            if want_final != before {
                crate::render_quality::set(want_final);
                editor.edited_at = Some(time.elapsed_secs_f64());
            }
            crate::console::controls(ui, &mut writers.console);
        });
        if console_expanded {
            ui.separator();
            crate::console::log_view(ui, writers.console.full, writers.console.level);
        }
    });
    // LEFT PANEL (U.3): the active tab's controls.
    let panel = egui::Panel::left("panel")
        .resizable(true)
        .default_size(440.0)
        .frame(panel_frame())
        .show(&mut viewport, |ui| {
            match *tab {
                Tab::Model => {
                    // FILE TABS (U.3.2): the open files as tabs + a ＋ that reopens the folder picker.
                    ui.horizontal_wrapped(|ui| {
                        for (i, path) in files.files.iter().enumerate() {
                            let name = path
                                .file_name()
                                .map(|s| s.to_string_lossy().into_owned())
                                .unwrap_or_else(|| "?".into());
                            let on = files.active == Some(i);
                            // Selected file = navy text on the gold selection pill (selection.bg_fill);
                            // filenames stay mixed-case (readouts, not chrome). No green, no fake-bold.
                            if ui.selectable_label(on, name).clicked() {
                                writers.switch.write(SwitchFile(i));
                            }
                        }
                        // The ＋ opens a .scad file picker — DESKTOP only (U.3.6). On web there's one
                        // presupplied file and no fs access, so the picker is hidden entirely. The
                        // picked file's FOLDER becomes the tab set (its siblings), that file active —
                        // so you open the model you're looking at, not just its containing directory.
                        if view.platform.shows_picker()
                            && ui
                                .button(icons::ADD)
                                .on_hover_text("open a .scad model")
                                .clicked()
                            && open_dialog.0.is_none()
                        {
                            // rfd's pick_file→path() is desktop-only; on wasm file-open is an
                            // <input type=file> byte read (W.3.4 host surface) and the picker's hidden
                            // anyway (shows_picker() == false), so this branch never runs there.
                            #[cfg(not(target_arch = "wasm32"))]
                            {
                                open_dialog.0 =
                                    Some(AsyncComputeTaskPool::get().spawn(async move {
                                        rfd::AsyncFileDialog::new()
                                            .add_filter("OpenSCAD source", &["scad"])
                                            .pick_file()
                                            .await
                                            .map(|h| h.path().to_path_buf())
                                    }));
                            }
                        }
                    });
                    ui.separator();
                    // Save (explicit, desktop) + jump to OpenSCAD. The buffer renders live; the file
                    // on disk only changes here. On save the live slicing config is BAKED into the
                    // .scad as a trailing `fab:config` comment block (W.3.8) — the one persistence
                    // mechanism both platforms share (web downloads the same bytes). `with_config_block`
                    // strips any prior block first, so re-saving replaces, never stacks.
                    ui.horizontal(|ui| {
                        // Save delivery splits per platform (W.3.13): native writes the file; the
                        // browser downloads the SAME config-baked bytes (there is no disk — this is
                        // W.3.8's "web downloads the same bytes", finally wired).
                        let save_hover = if cfg!(target_arch = "wasm32") {
                            "download .scad"
                        } else {
                            "save to disk"
                        };
                        if ui
                            .add_enabled(editor.dirty, egui::Button::new(icons::SAVE))
                            .on_hover_text(save_hover)
                            .clicked()
                        {
                            // Bake the CURRENT bed into the block too (W.3.8) — the model carries its
                            // own printer, so a web reload with no printers.toml still sizes right.
                            let printer = config::PrinterCfg {
                                bed: [
                                    scene.bed[0] as f64,
                                    scene.bed[1] as f64,
                                    scene.bed[2] as f64,
                                ],
                            };
                            let baked =
                                config::with_config_block(&editor.text, &parts.0, Some(printer));
                            #[cfg(not(target_arch = "wasm32"))]
                            if std::fs::write(&editor.path, baked).is_ok() {
                                editor.dirty = false;
                            }
                            #[cfg(target_arch = "wasm32")]
                            {
                                let name = editor
                                    .path
                                    .file_name()
                                    .and_then(|n| n.to_str())
                                    .filter(|n| !n.is_empty())
                                    .unwrap_or("model.scad");
                                if crate::web_host::download_bytes(
                                    name,
                                    "application/x-openscad",
                                    baked.as_bytes(),
                                ) {
                                    editor.dirty = false;
                                }
                            }
                        }
                        if editor.dirty {
                            ui.colored_label(
                                theme::GOLD_DIM,
                                format!("{} unsaved", icons::DOT), // icons::DOT — a raw bullet is tofu
                            );
                        }
                    });
                    // Save back to the site (W.5.8): web only, and only when the deep-link named a
                    // media item (else there's no item to update in place). Gold CTA; the status bar
                    // reports progress + result (gui-reactive-standard).
                    if view.save_target.0.is_some()
                        && ui
                            .add(
                                egui::Button::new(
                                    theme::chrome("Save to hotchkiss.io", 14.0).color(theme::NAVY),
                                )
                                .fill(theme::GOLD),
                            )
                            .on_hover_text("update this model's files on hotchkiss.io")
                            .clicked()
                    {
                        writers.cmd.write(PanelCmd::SaveToSite);
                    }
                    // The code editor — its buffer IS the render source (debounced preview, U.3.2).
                    // `auto_shrink` off + sizing to the remaining space so it FILLS the panel, not just
                    // the text height (else a short file leaves the panel half-empty). `both()` (not
                    // `vertical()`) so a long line SCROLLS horizontally inside the editor instead of
                    // pushing the resizable panel wider — the code editor scrolls, never wraps
                    // (highlight::scad_job), and without a horizontal bar the over-wide galley set the
                    // panel's min width and a drag-narrow snapped straight back.
                    egui::ScrollArea::both()
                        .auto_shrink([false, false])
                        .show(ui, |ui| {
                            // SCAD syntax highlighting (U.3.13): a layouter that lexes the buffer and
                            // paints each token by kind (fab-lang's own lexer → colors track the grammar).
                            let mut layouter =
                                |ui: &egui::Ui, buf: &dyn egui::TextBuffer, _w: f32| {
                                    let font = egui::TextStyle::Monospace.resolve(ui.style());
                                    let job = crate::highlight::scad_job(
                                        buf.as_str(),
                                        font,
                                        ui.visuals().text_color(),
                                    );
                                    ui.fonts_mut(|f| f.layout_job(job))
                                };
                            // `ui.add` (NOT `add_sized`): add_sized centres/justifies its child, which
                            // scrolls a long line to its MIDDLE on open — a code editor must sit at
                            // column 0 and scroll right from there. `desired_rows` fills the panel
                            // height so a short file doesn't leave it half-empty (what add_sized gave).
                            let row_h = ui.text_style_height(&egui::TextStyle::Monospace);
                            let rows = (ui.available_height() / row_h).floor().max(1.0) as usize;
                            let resp = ui.add(
                                egui::TextEdit::multiline(&mut editor.text)
                                    .code_editor()
                                    .desired_width(f32::INFINITY)
                                    .desired_rows(rows)
                                    .layouter(&mut layouter),
                            );
                            if resp.changed() {
                                editor.dirty = true;
                                editor.edited_at = Some(time.elapsed_secs_f64());
                            }
                        });
                }
                Tab::Customize => {
                    // Params → widgets → source-splice back into the buffer (X.2); the debounced
                    // preview re-render (shared with the editor) does the rest.
                    crate::customize::customize_panel(
                        ui,
                        &cv_params,
                        &mut editor,
                        time.elapsed_secs_f64(),
                        cv_defaults,
                    );
                }
                Tab::Parts => {
                    // Printer bed (W.3.8): the build volume every part slices + packs against — a
                    // per-MODEL slicing input (not a global), so it lives on the Parts tab and persists
                    // in the .scad's fab:config on Save. That's the web's only bed source (no
                    // printers.toml in the browser), so a `?model=` reload sizes right. Edit a COPY so
                    // DragValue's mutable borrow can't false-trip SceneCfg's change detection — only a
                    // REAL delta writes back (→ `resize_bed` reshapes the slab + re-arms auto-plan).
                    {
                        let mut bed = scene.bed;
                        ui.horizontal(|ui| {
                            ui.label(theme::chrome("printer bed", 15.0).color(theme::NAVY));
                            for (axis, i) in [("X", 0usize), ("Y", 1), ("Z", 2)] {
                                ui.label(egui::RichText::new(axis).small().weak());
                                ui.add(
                                    egui::DragValue::new(&mut bed[i])
                                        .speed(1.0)
                                        .range(10.0..=1000.0)
                                        .fixed_decimals(0)
                                        .suffix(" mm"),
                                );
                            }
                        });
                        if bed != scene.bed {
                            scene.set_configured_bed(bed); // slaves the export plate to the new bed
                            editor.dirty = true; // enable Save so the new bed bakes into fab:config
                        }
                    }
                    ui.separator();
                    // THE DRILL (U.3.3): part → cut → connector, top to bottom. A collapsing section
                    // per top-level part (green + bold = active); its body flattens to that part's
                    // cuts; expanding a cut (▼) reveals its connectors inline. The active part drives
                    // the slice systems + cut-plane overlays, so an edit reslices the right part.
                    ui.label(
                        egui::RichText::new("parts · cuts · connectors")
                            .small()
                            .weak(),
                    );
                    let n = parts.0.len();
                    let mut autoplace_req = false;
                    for i in 0..n {
                        let is_active = active_part.0 == i;
                        // max with the part's component count so a PRESLICED part (0 cuts, N disjoint
                        // pieces) reads "N pcs", not "1 pc" — piece_estimate alone ignores components.
                        let pcs = piece_estimate(&parts.0[i].cuts).max(parts.0[i].pieces);
                        let label = format!(
                            "{} · {} pc{}",
                            part_label(&parts.0[i].name, i),
                            pcs,
                            if pcs == 1 { "" } else { "s" }
                        );
                        // Oswald caps header (chrome). Active cue = a painted gold left-rule +
                        // default-open; NO green, NO fake-bold (Oswald is 400 only).
                        let header = theme::chrome(&label, 15.0).color(theme::NAVY);
                        let mut select = false;
                        let resp = egui::CollapsingHeader::new(header)
                            .id_salt(("part", i))
                            .default_open(is_active)
                            .show(ui, |ui| {
                                select |= part_cut_editor(
                                    ui,
                                    &mut parts.0[i],
                                    i,
                                    is_active,
                                    &mut edit,
                                    &mut active,
                                    &mut to_remove,
                                    &mut autoplace_req,
                                );
                            });
                        if is_active {
                            // gold left-rule marks the active part (matches the active-cut rule)
                            let r = resp.header_response.rect;
                            ui.painter().vline(
                                r.left(),
                                r.y_range(),
                                egui::Stroke::new(2.0, theme::GOLD),
                            );
                        }
                        if select || resp.header_response.clicked() {
                            active_part.0 = i;
                            parts.set_changed(); // a pure selection must refresh the active-part visuals
                        }
                    }
                    // An Auto-place click inside the drill bubbles up here (the writer can't cross the
                    // part-borrow into `part_cut_editor`).
                    if autoplace_req {
                        writers.autoplace.write(AutoPlace);
                    }
                    ui.separator();
                    // Slicing itself is reactive (background reslice on cut changes) — these are the
                    // only two Parts actions, and each ALWAYS has an effect: no dead buttons (U.3.15).
                    let (has_cuts, spread) = {
                        let p = &parts.0[active_part.0];
                        (p.cuts.list.iter().any(|c| c.enabled), p.spread)
                    };
                    // Reset-to-auto: throw away this part's cuts+connectors and re-derive the full plan
                    // (fit-to-bed cuts + auto-placed connectors, or WHOLE if it fits).
                    if ui
                        .button(format!("{}  Reset to auto", icons::RESTART))
                        .clicked()
                    {
                        writers.cmd.write(PanelCmd::AutoSlice);
                    }
                    // Explode is a per-part VIEW toggle, enabled only when the part has pieces to fan —
                    // a part that fits the bed is whole, so there's nothing to explode.
                    if ui
                        .add_enabled(
                            has_cuts,
                            egui::Button::new(if spread > 0.0 { "Assemble" } else { "Explode" }),
                        )
                        .clicked()
                    {
                        writers.cmd.write(PanelCmd::ToggleView);
                    }
                    // Slice summary (mockup's eg-status): part count + estimated piece total (each
                    // part's cut estimate, floored by its presliced component count — see the header).
                    let total: usize = parts
                        .0
                        .iter()
                        .map(|p| piece_estimate(&p.cuts).max(p.pieces))
                        .sum();
                    ui.label(
                        egui::RichText::new(format!(
                            "{n} part{} · {total} pieces",
                            if n == 1 { "" } else { "s" }
                        ))
                        .small()
                        .weak(),
                    );
                }
                Tab::Orientation => {
                    ui.label(egui::RichText::new("print orientation").small().weak());
                    ui.label(
                        egui::RichText::new(
                            "click a piece in the view to set which face prints down",
                        )
                        .small()
                        .weak(),
                    );
                    ui.separator();
                    // Every printable piece across ALL parts (co-pack), each flagged flat (a manual
                    // orientation set) vs auto (still the least-support auto-pick). The mode + 3D
                    // click-to-orient already run while this tab is up; this is the readout + per-piece
                    // reset. `PrintPieces` is None until the first slice lands.
                    match view.print_pieces.0.as_ref() {
                        None => {
                            ui.label(
                                egui::RichText::new("slice a part first — no pieces yet")
                                    .small()
                                    .weak(),
                            );
                        }
                        Some(pieces) => {
                            let mut flat = 0usize;
                            let mut nth: std::collections::HashMap<usize, usize> =
                                std::collections::HashMap::new();
                            for (part, pp) in pieces {
                                let Some(p) = parts.0.get(*part) else {
                                    continue;
                                };
                                let key = (pp.piece, pp.comp);
                                let manual = p.orient.manual.contains(&key);
                                if manual {
                                    flat += 1;
                                }
                                let n = {
                                    let c = nth.entry(*part).or_insert(0);
                                    *c += 1;
                                    *c
                                };
                                let label = format!("{} · pc {}", part_label(&p.name, *part), n);
                                ui.horizontal(|ui| {
                                    ui.label(label);
                                    ui.with_layout(
                                        egui::Layout::right_to_left(egui::Align::Center),
                                        |ui| {
                                            if manual {
                                                // manual → seated flat; a click resets it to the auto-pick.
                                                if ui
                                                    .small_button(icons::RESTART)
                                                    .on_hover_text("reset to auto")
                                                    .clicked()
                                                {
                                                    reset_orient = Some((*part, key));
                                                }
                                                ui.label(
                                                    egui::RichText::new(format!(
                                                        "flat {}",
                                                        icons::CHECK
                                                    ))
                                                    .monospace()
                                                    .color(theme::NAVY)
                                                    .strong(),
                                                );
                                            } else {
                                                ui.label(
                                                    egui::RichText::new("auto")
                                                        .monospace()
                                                        .color(theme::GOLD_DIM),
                                                );
                                            }
                                        },
                                    );
                                });
                            }
                            ui.separator();
                            ui.label(
                                egui::RichText::new(format!(
                                    "{} pieces · {} seated flat",
                                    pieces.len(),
                                    flat
                                ))
                                .small()
                                .weak(),
                            );
                        }
                    }
                }
                Tab::Export => {
                    // The co-pack preview metric (U.3.5): `estimate_copack` keeps this live as pieces +
                    // orientations change — no button to compute it. Then the two output actions.
                    ui.label(egui::RichText::new("co-packed plates").small().weak());
                    match &view.copack.summary {
                        Some(s) => {
                            ui.label(
                                egui::RichText::new(format!(
                                    "{} plates · {} pieces · fits {:.0}×{:.0}",
                                    s.plates, s.pieces, view.copack.bed[0], view.copack.bed[1]
                                ))
                                .strong(),
                            );
                            ui.label(
                                egui::RichText::new(format!(
                                    "{}% full",
                                    (s.fill * 100.0).round() as i32
                                ))
                                .small()
                                .weak(),
                            );
                        }
                        None => {
                            ui.label(
                                egui::RichText::new("slice a part first — nothing to pack yet")
                                    .small()
                                    .weak(),
                            );
                        }
                    }
                    ui.separator();
                    // CTA buttons: gold fill + navy Oswald caption (the site's accent button).
                    if ui
                        .add(
                            egui::Button::new(
                                theme::chrome("Export plates (3MF)", 14.0).color(theme::NAVY),
                            )
                            .fill(theme::GOLD),
                        )
                        .clicked()
                    {
                        writers.cmd.write(PanelCmd::Export);
                    }
                    // Desktop: publish a NEW hotchkiss.io gallery item (shells OpenSCAD + native HTTP).
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        if ui
                            .add(
                                egui::Button::new(
                                    theme::chrome("Publish -> hotchkiss.io", 14.0)
                                        .color(theme::NAVY),
                                )
                                .fill(theme::GOLD),
                            )
                            .clicked()
                        {
                            writers.cmd.write(PanelCmd::Publish);
                        }
                    }
                    // Web (W.3.18): push the finished result back to the item it came from — the save-back
                    // (source + mesh variants + the printable plate, since the pieces live on this tab).
                    // Only when opened from a media item (save_target set); creating a NEW item stays
                    // desktop-only.
                    #[cfg(target_arch = "wasm32")]
                    {
                        if view.save_target.0.is_some()
                            && ui
                                .add(
                                    egui::Button::new(
                                        theme::chrome("Update -> hotchkiss.io", 14.0)
                                            .color(theme::NAVY),
                                    )
                                    .fill(theme::GOLD),
                                )
                                .on_hover_text(
                                    "update this model's files on hotchkiss.io (meshes + plate)",
                                )
                                .clicked()
                        {
                            writers.cmd.write(PanelCmd::SaveToSite);
                        }
                    }
                }
            }
            // Fill the panel to full height on every tab so its frame reaches the status bar (U.3.2).
            ui.add_space(ui.available_height());
        });
    if let Some((p, idx)) = to_remove
        && let Some(part) = parts.0.get_mut(p)
    {
        remove_cut(&mut part.cuts, &mut part.conns, idx);
    }
    if let Some((part, key)) = reset_orient {
        if let Some(p) = parts.0.get_mut(part) {
            p.orient.reset(key);
        }
        parts.set_changed(); // re-seat this piece at the auto-pick (sync_orientation guards on is_changed)
    }
    seam.width_px = panel.response.rect.width() * ctx.pixels_per_point();
    seam.top_px = top.response.rect.height() * ctx.pixels_per_point();
    seam.bottom_px = bottom.response.rect.height() * ctx.pixels_per_point();
    seam.over_ui = ctx.egui_wants_pointer_input() || ctx.is_pointer_over_egui();
}

/// Render one part's cut + connector drill — the middle and inner levels of the part → cut →
/// connector tree (U.3.3). Each cut is a flat stack-order row whose `▸/▼` triangle expands its
/// connectors inline (and drives the 2D face-on cross-section editor through `edit`); a trailing
/// `+X/+Y/+Z` strip adds a plane. Returns `true` if the user TOUCHED anything, so the caller makes
/// this part active and the reactive slice follows the edit. `part_idx` tags a deferred delete with
/// its owner; `autoplace_req` bubbles an Auto-place click up to the caller's message writer (which
/// can't cross the `part` borrow).
#[allow(
    clippy::too_many_arguments,
    reason = "the drill threads one part plus edit/active/remove/autoplace channels; a bundle struct just relocates the arity, not the noise"
)]
pub(crate) fn part_cut_editor(
    ui: &mut egui::Ui,
    part: &mut Part,
    part_idx: usize,
    is_active_part: bool,
    edit: &mut EditCut,
    active: &mut ActiveConn,
    to_remove: &mut Option<(usize, usize)>,
    autoplace_req: &mut bool,
) -> bool {
    let mut touched = false;
    // CUTS — a flat stack-order list (the connector `.cut` field indexes THIS order, so don't
    // reorder). Only the active part edits connectors, so its `▼` state gates the inline drill.
    let n = part.cuts.list.len();
    for idx in 0..n {
        let axis = part.cuts.list[idx].axis;
        let editing = is_active_part && edit.0 == Some(idx);
        let is_cut_active = idx == part.cuts.active;
        let cut_row = ui.horizontal(|ui| {
            // Expand this cut's connectors (and enter the 2D face-on editor — both ride `edit`). A real
            // Material Symbols glyph from the build.rs-managed icon font: chevron_right when collapsed,
            // expand_more when open (U.2.1). Frameless clickable label = a bare chevron, per the mockup.
            let glyph = if editing {
                icons::EXPAND_MORE
            } else {
                icons::CHEVRON_RIGHT
            };
            if ui
                .add(egui::Label::new(glyph).sense(egui::Sense::click()))
                .clicked()
            {
                edit.0 = if editing { None } else { Some(idx) };
                part.cuts.active = idx;
                touched = true;
            }
            let name = format!("{} cut @", axis.label());
            // Active row = navy + weight (a readout, not chrome — stays mixed-case Ubuntu-Light); the
            // gold accent is the painted left-rule below, matching the active-part header.
            ui.label(if is_cut_active {
                egui::RichText::new(name).color(theme::NAVY).strong()
            } else {
                egui::RichText::new(name)
            });
            let mut at = part.cuts.list[idx].at;
            if ui.add(egui::DragValue::new(&mut at).speed(0.5)).changed() {
                part.cuts.list[idx].at = clamp_to_bounds(at, axis, &part.bounds);
                part.cuts.active = idx;
                touched = true;
            }
            let en = part.cuts.list[idx].enabled;
            // Eye / eye-off = the cut's in/out of the slice (U.2 icon swap; hover names it).
            if ui
                .selectable_label(en, if en { icons::EYE } else { icons::EYE_OFF })
                .on_hover_text(if en { "in the slice" } else { "disabled" })
                .clicked()
            {
                part.cuts.list[idx].enabled = !en;
                touched = true;
            }
            if ui
                .button(egui::RichText::new(icons::DELETE).color(theme::DANGER))
                .on_hover_text("delete cut")
                .clicked()
            {
                *to_remove = Some((part_idx, idx));
                touched = true;
            }
        });
        if is_cut_active {
            // gold left-rule marks the active cut (matches the active-part header rule)
            ui.painter().vline(
                cut_row.response.rect.left(),
                cut_row.response.rect.y_range(),
                egui::Stroke::new(2.0, theme::GOLD),
            );
        }
        // CONNECTORS — inline under the expanded cut (the old Connectors mode, now nested). Sets the
        // active connector TYPE + does auto-place / clear for THIS cut; click-to-place lives in the
        // 2D editor on the same `edit` state.
        if editing {
            ui.indent(("conn", idx), |ui| {
                ui.label(egui::RichText::new("connectors — this cut").small().weak());
                ui.horizontal(|ui| {
                    if ui
                        .selectable_label(active.kind == fab::ConnKind::Onion, "Onion")
                        .clicked()
                    {
                        active.kind = fab::ConnKind::Onion;
                    }
                    if ui
                        .selectable_label(active.kind == fab::ConnKind::Bolt, "Bolt")
                        .clicked()
                    {
                        active.kind = fab::ConnKind::Bolt;
                    }
                });
                if active.kind == fab::ConnKind::Bolt {
                    ui.horizontal(|ui| {
                        for s in [Screw::M3, Screw::M4, Screw::M5] {
                            if ui.selectable_label(active.screw == s, s.label()).clicked() {
                                active.screw = s;
                            }
                        }
                    });
                }
                ui.horizontal(|ui| {
                    if ui.button("Auto-place").clicked() {
                        *autoplace_req = true;
                    }
                    if ui.button("Clear").clicked() {
                        part.conns.list.retain(|c| c.cut != idx);
                    }
                });
            });
        }
    }
    // ADD PLANES — one combined +X/+Y/+Z strip (replaces the old per-axis "+" sections), matching
    // the v4 mockup. A new plane drops at the part's mid-span on that axis.
    ui.horizontal(|ui| {
        for axis in [Axis::X, Axis::Y, Axis::Z] {
            if ui
                .button(format!("{} {}", icons::ADD, axis.label()))
                .clicked()
                && let Some((mn, mx)) = part.bounds.0
            {
                let at = comp((mn + mx) * 0.5, axis.index());
                part.cuts.list.push(CutDef {
                    axis,
                    at,
                    enabled: true,
                });
                part.cuts.active = part.cuts.list.len() - 1;
                touched = true;
            }
        }
    });
    touched
}

/// The accordion label for part `i`: its provenance name (the top-level module/function that made
/// it) capped to a stable width + an ordinal suffix — `wall_sliced·1`, `frame·2` — or a generic
/// `Part N` when the part is anonymous (a bare block / an ambiguous split). The suffix keeps labels
/// short + uniform and disambiguates two parts from the SAME module (T.2b).
pub(crate) fn part_label(name: &Option<String>, i: usize) -> String {
    const CAP: usize = 12; // chars, before the ·ordinal — keeps the accordion column tidy
    match name {
        Some(n) if n.chars().count() > CAP => {
            let short: String = n.chars().take(CAP - 1).collect();
            format!("{short}…·{}", i + 1)
        }
        Some(n) => format!("{n}·{}", i + 1),
        None => format!("Part {}", i + 1),
    }
}

/// A rough printable-piece count for a part's cut stack — the product over axes of (enabled cuts on
/// that axis + 1). Ignores connected-components (a presliced blob reads as 1 until sliced), so it's
/// a fast accordion label, not the exact plate count.
pub(crate) fn piece_estimate(cuts: &Cuts) -> usize {
    [Axis::X, Axis::Y, Axis::Z]
        .iter()
        .map(|&ax| {
            cuts.list
                .iter()
                .filter(|c| c.enabled && c.axis == ax)
                .count()
                + 1
        })
        .product()
}

/// Fire `fab-gui:ready` — a `document` CustomEvent — ONCE, when the first themed egui frame is up: the
/// host page's cue to remove its boot splash (docs/web-embed.md). Runs right after `panel_ui` in the
/// egui pass, so by the time it fires the tool UI has been submitted for the frame. No-op on desktop —
/// there's no host page to tell. The `Local` latches it to a single dispatch for the app's lifetime.
pub(crate) fn signal_ready(mut fired: Local<bool>, mut contexts: EguiContexts) {
    if *fired || contexts.ctx_mut().is_err() {
        return; // egui context not up yet — wait for a real painted frame
    }
    *fired = true;
    #[cfg(target_arch = "wasm32")]
    if let Some(doc) = web_sys::window().and_then(|w| w.document())
        && let Ok(ev) = web_sys::CustomEvent::new("fab-gui:ready")
    {
        let _ = doc.dispatch_event(&ev);
    }
}
