//! Build-time Material Symbols font pipeline (U.2.1).
//!
//! Produces the tiny committed icon subset `assets/fonts/MaterialSymbols-subset.ttf` from the upstream
//! Material Symbols variable font — DETERMINISTICALLY: the same manifest always yields byte-identical
//! bytes (pinned source by sha256, fixed axis instance, `SOURCE_DATE_EPOCH=0` on every fonttools call).
//!
//! The committed subset IS the cache. A normal or CI build finds a matching stamp and does NOTHING —
//! no network, no fonttools, so the just-won green CI stays offline-clean. Only editing the glyph
//! MANIFEST below (or the source pin) triggers a regen: download → instance at fixed axes → subset.
//! Regen needs `curl`, `fonttools`, `pyftsubset`, `shasum` on PATH; the dev commits the regenerated
//! subset + stamp. `.subset-stamp` is written by this script so its format can't drift from the check.

use std::path::{Path, PathBuf};
use std::process::Command;

/// (const-name, codepoint) — the SINGLE source of truth. Drives BOTH the subset `--unicodes` and the
/// generated Rust glyph consts, so the font and the code that draws it can never drift.
const MANIFEST: &[(&str, u32)] = &[
    ("ADD", 0xe145),           // plus
    ("DELETE", 0xe872),        // trash
    ("EYE", 0xe8f4),           // visible (on)
    ("EYE_OFF", 0xe8f5),       // hidden (off)
    ("PLUG_CONNECT", 0xf35a),  // connector
    ("CHEVRON_RIGHT", 0xe5cc), // cut collapsed
    ("EXPAND_MORE", 0xe5cf),   // cut expanded
];

/// Upstream Material Symbols Outlined variable font, PINNED to a commit SHA + content sha256
/// (content-addressed = a deterministic input; a moved/updated upstream trips the sha256 check).
const SOURCE_URL: &str = "https://raw.githubusercontent.com/google/material-design-icons/819d78680a849ceef4c78f863d8753e3160b7c89/variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.ttf";
const SOURCE_SHA256: &str = "e67c84976868d2016a4bb5e4daacd03d92e0c58c935ccd7091fe3b6230761552";
/// The static instance the subset is cut at — Material Symbols Outlined, Regular weight, optical size 24.
const AXES: &[(&str, &str)] = &[("FILL", "0"), ("wght", "400"), ("GRAD", "0"), ("opsz", "24")];

const SUBSET_REL: &str = "assets/fonts/MaterialSymbols-subset.ttf";
const STAMP_REL: &str = "assets/fonts/.subset-stamp";

fn main() {
    // The manifest + pins all live in this file, so a change here is the only regen trigger.
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let subset = manifest_dir.join(SUBSET_REL);
    let stamp = manifest_dir.join(STAMP_REL);

    // Glyph consts are cheap + std-only — regenerate every build so they always match the manifest.
    generate_consts();

    let want = stamp_string();
    let have = std::fs::read_to_string(&stamp).unwrap_or_default();
    if subset.exists() && have == want {
        return; // cache hit — committed subset is current. No network, no tools.
    }

    // REGEN — the manifest or source pin changed. Requires curl/fonttools/pyftsubset/shasum.
    eprintln!("fab-gui build.rs: regenerating {SUBSET_REL} (manifest/source changed)");
    regen(&subset);
    std::fs::write(&stamp, want).expect("write .subset-stamp");
}

/// The stamp is a canonical plain-text descriptor of everything that determines the subset bytes.
/// Plain string compare (no hashing) keeps the fast path std-only.
fn stamp_string() -> String {
    let glyphs: Vec<String> = MANIFEST.iter().map(|(_, c)| format!("{c:04x}")).collect();
    let axes: Vec<String> = AXES.iter().map(|(a, v)| format!("{a}={v}")).collect();
    format!(
        "v1\nsource={SOURCE_URL}\nsha256={SOURCE_SHA256}\naxes={}\nglyphs={}\n",
        axes.join(","),
        glyphs.join(",")
    )
}

/// Emit `$OUT_DIR/icon_glyphs.rs` — one `pub const <NAME>: &str = "\u{cp}";` per manifest entry.
fn generate_consts() {
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("icon_glyphs.rs");
    let mut src = String::from("// @generated by build.rs from the Material Symbols manifest — do not edit.\n");
    for (name, cp) in MANIFEST {
        src.push_str(&format!("pub const {name}: &str = \"\\u{{{cp:x}}}\";\n"));
    }
    std::fs::write(&out, src).expect("write icon_glyphs.rs");
}

/// Download (cached, sha256-verified) → instance at fixed axes → subset. Every fonttools call runs
/// under `SOURCE_DATE_EPOCH=0` so the `head.modified` timestamp is fixed and the output is byte-stable.
fn regen(subset: &Path) {
    let cache = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("font-cache");
    std::fs::create_dir_all(&cache).expect("create font-cache");

    // 1. Download the full variable font, keyed by its pinned hash; verify before use.
    let full = cache.join(format!("ms-{}.ttf", &SOURCE_SHA256[..16]));
    if !full.exists() || sha256(&full) != SOURCE_SHA256 {
        let ok = Command::new("curl")
            .args(["-sL", "--fail", "--max-time", "180", "-o"])
            .arg(&full)
            .arg(SOURCE_URL)
            .status()
            .expect("run curl (needed to fetch the Material Symbols source font)")
            .success();
        assert!(ok, "curl failed to download the Material Symbols source font");
        let got = sha256(&full);
        assert_eq!(
            got, SOURCE_SHA256,
            "downloaded font sha256 mismatch — upstream moved; update SOURCE_URL + SOURCE_SHA256"
        );
    }

    // 2. Instance the variable font to a static instance at the fixed axes.
    let static_font = cache.join("ms-static.ttf");
    let axis_args: Vec<String> = AXES.iter().map(|(a, v)| format!("{a}={v}")).collect();
    let ok = Command::new("fonttools")
        .env("SOURCE_DATE_EPOCH", "0")
        .arg("varLib.instancer")
        .arg(&full)
        .args(&axis_args)
        .arg("-q")
        .arg("-o")
        .arg(&static_font)
        .status()
        .expect("run fonttools varLib.instancer (install fonttools to regenerate the icon subset)")
        .success();
    assert!(ok, "fonttools varLib.instancer failed");

    // 3. Subset the static instance to exactly the manifest codepoints (cmap preserved for egui).
    let unicodes = MANIFEST
        .iter()
        .map(|(_, c)| format!("{c:x}"))
        .collect::<Vec<_>>()
        .join(",");
    let ok = Command::new("pyftsubset")
        .env("SOURCE_DATE_EPOCH", "0")
        .arg(&static_font)
        .arg(format!("--unicodes={unicodes}"))
        .arg("--no-hinting")
        .arg("--desubroutinize")
        .arg(format!("--output-file={}", subset.display()))
        .status()
        .expect("run pyftsubset (install fonttools to regenerate the icon subset)")
        .success();
    assert!(ok, "pyftsubset failed");
}

/// sha256 of a file via `shasum -a 256` (only reached on regen, never on the cache-hit fast path).
fn sha256(path: &Path) -> String {
    let out = Command::new("shasum")
        .args(["-a", "256"])
        .arg(path)
        .output()
        .expect("run shasum");
    String::from_utf8_lossy(&out.stdout)
        .split_whitespace()
        .next()
        .unwrap_or_default()
        .to_string()
}
