//! TB e2e: the WHOLE self-update path against a localhost release — manifest (generated by the
//! SAME script CI runs, so the published shape and the parsed shape cannot drift), minisign
//! signature (built byte-for-byte the way cargo-packager's `sign_outputs` builds it: base64 of the
//! signature box over the raw tar.gz), download, verify, and a REAL bundle swap on disk. What it
//! can't cover: the GitHub redirect chain and the notarized-bytes question — those only exist on a
//! real release, which is why the first tagged release after TB gets a manual update-through-the-app
//! check (docs/packaging.md "auto-update").
//!
//! macOS only, like the updater itself.
#![cfg(target_os = "macos")]

use std::fs;
use std::io::{Read, Write};
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::Command;

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as B64;
use cargo_packager_updater::{Config, UpdaterBuilder, semver::Version, url::Url};

/// A fake `.app` whose "binary" is a marker file — enough bundle shape for the updater's walk-up
/// (`Contents/MacOS/<exe>`), tiny enough to tar in-memory-fast.
fn write_bundle(root: &Path, marker: &str) -> PathBuf {
    let macos = root.join("fab-scad.app/Contents/MacOS");
    fs::create_dir_all(&macos).unwrap();
    fs::write(macos.join("fab-gui"), marker).unwrap();
    fs::write(
        root.join("fab-scad.app/Contents/Info.plist"),
        "<plist/>", // present for shape; the updater never parses it
    )
    .unwrap();
    root.join("fab-scad.app")
}

/// One-connection-at-a-time HTTP/1.1 server on an ephemeral port — serves the manifest and the
/// tarball, which is all the updater requests. Hand-rolled on std so the test adds no server dep.
fn serve(dir: PathBuf) -> u16 {
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    std::thread::spawn(move || {
        for stream in listener.incoming() {
            let Ok(mut stream) = stream else { continue };
            // Read the request head (path is all we need; both requests are bodyless GETs).
            let mut buf = [0u8; 4096];
            let mut head = Vec::new();
            while !head.windows(4).any(|w| w == b"\r\n\r\n") {
                match stream.read(&mut buf) {
                    Ok(0) | Err(_) => break,
                    Ok(n) => head.extend_from_slice(&buf[..n]),
                }
            }
            let request = String::from_utf8_lossy(&head);
            let path = request.split_whitespace().nth(1).unwrap_or("/").to_string();
            let (body, ctype) = match path.as_str() {
                "/latest.json" => (
                    fs::read(dir.join("latest.json")).unwrap(),
                    "application/json",
                ),
                "/fab-scad.app.tar.gz" => (
                    fs::read(dir.join("fab-scad.app.tar.gz")).unwrap(),
                    "application/octet-stream",
                ),
                _ => (b"not found".to_vec(), "text/plain"),
            };
            let status = if path.starts_with("/latest") || path.starts_with("/fab-scad") {
                "200 OK"
            } else {
                "404 Not Found"
            };
            let _ = write!(
                stream,
                "HTTP/1.1 {status}\r\ncontent-type: {ctype}\r\ncontent-length: {}\r\nconnection: close\r\n\r\n",
                body.len()
            );
            let _ = stream.write_all(&body);
        }
    });
    port
}

#[test]
fn manifest_sign_download_verify_swap() {
    let tmp = std::env::temp_dir().join(format!("fab-update-e2e-{}", std::process::id()));
    let _ = fs::remove_dir_all(&tmp);
    fs::create_dir_all(&tmp).unwrap();

    // The "installed" 1.0.0 bundle the updater will swap, and the 9.9.9 bundle "on the release".
    let installed = write_bundle(&tmp.join("install"), "OLD");
    write_bundle(&tmp.join("new"), "NEW");

    // Tar exactly the way cargo-packager's create_tar_from_dir does: the bundle dir as the single
    // top-level entry (the updater strips that first component on extract).
    let tarball = tmp.join("fab-scad.app.tar.gz");
    // COPYFILE_DISABLE: without it macOS bsdtar prepends AppleDouble `._fab-scad.app` entries,
    // which the updater's strip-first-component extraction turns into an unpackable empty path
    // (found the hard way: PermissionDenied mid-swap). The real artifact comes from the Rust tar
    // crate, which never writes them — this env var makes bsdtar match that layout.
    let status = Command::new("tar")
        .env("COPYFILE_DISABLE", "1")
        .args(["-C"])
        .arg(tmp.join("new"))
        .args(["-czf"])
        .arg(&tarball)
        .arg("fab-scad.app")
        .status()
        .unwrap();
    assert!(status.success(), "tar failed");

    // Fresh throwaway keypair + signature, mirroring packager sign.rs: sig file = base64 of the
    // minisign signature box over the raw tar.gz bytes; pubkey = base64 of the public-key box.
    let minisign::KeyPair { pk, sk } =
        minisign::KeyPair::generate_encrypted_keypair(Some(String::new())).unwrap();
    let tar_bytes = fs::read(&tarball).unwrap();
    let sig_box = minisign::sign(
        None,
        &sk,
        std::io::Cursor::new(&tar_bytes),
        Some("timestamp:0\tfile:fab-scad.app.tar.gz"),
        Some("signature from cargo-packager secret key"),
    )
    .unwrap();
    let sig_file = tmp.join("fab-scad.app.tar.gz.sig");
    fs::write(&sig_file, B64.encode(sig_box.to_string())).unwrap();
    let pubkey = B64.encode(pk.to_box().unwrap().to_string());

    // Port first (the manifest embeds it), then the REAL manifest generator CI uses.
    let port = serve(tmp.clone());
    let script =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../packaging/macos/make-update-manifest.sh");
    let status = Command::new("bash")
        .arg(script)
        .args([
            "9.9.9",
            &format!("http://127.0.0.1:{port}/fab-scad.app.tar.gz"),
        ])
        .arg(&sig_file)
        .arg(tmp.join("latest.json"))
        .arg("e2e notes")
        .status()
        .unwrap();
    assert!(status.success(), "make-update-manifest.sh failed");

    // The real updater crate, pointed at the fake install + the localhost release.
    let config = Config {
        endpoints: vec![Url::parse(&format!("http://127.0.0.1:{port}/latest.json")).unwrap()],
        pubkey,
        windows: None,
    };
    let updater = UpdaterBuilder::new(Version::new(1, 0, 0), config)
        .executable_path(installed.join("Contents/MacOS/fab-gui"))
        .build()
        .unwrap();

    let update = updater
        .check()
        .expect("check against local manifest")
        .expect("9.9.9 > 1.0.0 must offer an update");
    assert_eq!(update.version, "9.9.9");
    assert_eq!(update.body.as_deref(), Some("e2e notes"));

    // download() verifies the minisign signature before returning; install() swaps the bundle.
    update
        .download_and_install()
        .expect("verified download + bundle swap");

    let swapped = fs::read_to_string(installed.join("Contents/MacOS/fab-gui")).unwrap();
    assert_eq!(swapped, "NEW", "the installed bundle was not swapped");

    // A tampered tarball must FAIL verification — the negative half of the signature story.
    fs::write(&tarball, b"evil bytes").unwrap();
    let redo = updater.check().unwrap().expect("still offers 9.9.9");
    assert!(
        redo.download().is_err(),
        "tampered payload must not verify against the pinned pubkey"
    );

    let _ = fs::remove_dir_all(&tmp);
}
