//! Codegen for the slicing driver (5.2): turn a `[slicing]` spec into a `slice()`/connector
//! `.scad` that `fab slice` renders. Pure string-building — the IO (freeze source, render)
//! lives in `slice_cmd`. This is the GUI ↔ fab contract: the GUI edits the spec, this
//! reproduces the same SCAD headlessly, so preview and `fab slice` are one path.

use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{bail, Context, Result};

use crate::manifest::{Connector, Slicing};
use crate::openscad::Openscad;

const AXIS: [&str; 3] = ["RIGHT", "BACK", "UP"];

/// Freeze `source` to a mesh, generate the slicer driver from `spec`, render the pieces.
/// Returns the sliced STL path. The shared slice flow — `fab slice` and the GUI both call it.
pub fn slice_part(
    oscad: &Openscad,
    source: &Path,
    spec: &Slicing,
    spread: f64,
    out_dir: &Path,
    timeout: Duration,
) -> Result<PathBuf> {
    std::fs::create_dir_all(out_dir).with_context(|| format!("creating {}", out_dir.display()))?;
    let stem = source
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "part".into());

    // Freeze the source to a mesh (slicing the frozen STL stays linear — no 2^N).
    let source_stl = out_dir.join(format!("{stem}.stl"));
    let f = oscad.render(source, &source_stl, timeout)?;
    if !f.ok {
        bail!("source render failed: {}", source.display());
    }

    // Generate the driver from the spec (imports the frozen mesh by name) and render it.
    let driver = driver_scad(spec, &format!("{stem}.stl"), spread)?;
    let driver_path = out_dir.join(format!("{stem}-sliced.scad"));
    std::fs::write(&driver_path, driver)
        .with_context(|| format!("writing {}", driver_path.display()))?;
    let sliced = out_dir.join(format!("{stem}-sliced.stl"));
    let r = oscad.render(&driver_path, &sliced, timeout)?;
    if !r.ok {
        bail!("slice render failed");
    }
    Ok(sliced)
}

/// Format a coordinate without a trailing `.0` for whole numbers (tidy generated SCAD).
fn n(x: f64) -> String {
    if x.fract() == 0.0 {
        format!("{}", x as i64)
    } else {
        format!("{x}")
    }
}

/// Generate the driver: nested `slice()` per axis around a `diff()` of the imported source
/// minus the connectors. `source` is the import path, relative to the driver file.
pub fn driver_scad(s: &Slicing, source: &str, spread: f64) -> Result<String> {
    // Group cut positions by axis, ascending (slice() requires ascending cuts).
    let mut by_axis: [Vec<f64>; 3] = [Vec::new(), Vec::new(), Vec::new()];
    for c in &s.cut {
        by_axis[c.axis_index()?].push(c.at());
    }
    for v in by_axis.iter_mut() {
        v.sort_by(|a, b| a.partial_cmp(b).unwrap());
    }

    let mut slices = String::new();
    for (ax, cuts) in by_axis.iter().enumerate() {
        if !cuts.is_empty() {
            let list = cuts.iter().map(|&x| n(x)).collect::<Vec<_>>().join(", ");
            // Onion joints ride slice()'s per-piece `connectors`; bolt/pin stay in the diff below.
            let onions = onion_param(s, ax)?;
            slices += &format!(
                "slice([{list}], axis = {}, spread = {}, connectors = {onions})\n",
                AXIS[ax],
                n(spread)
            );
        }
    }
    if slices.is_empty() {
        bail!("[slicing] has no cuts");
    }

    // `force_tag()` pulls the raw `import()` mesh into BOSL2's tag system — without it `diff()`
    // doesn't see the import as keep geometry and the connectors don't carve (BOSL2's own
    // attachable primitives are tagged automatically; `import()` is not).
    let mut body = String::from("tag_scope() diff() {\n");
    body += &format!("    force_tag() import(\"{source}\");\n");
    for c in &s.connector {
        if c.kind != "onion" {
            body += &connector_line(s, c)?; // bolt/pin: symmetric pre-slice negatives
        }
    }
    body += "}\n";

    Ok(format!(
        "// generated by `fab slice` from project.toml [slicing] — edits go in the spec, not here.\n\
         include <slicer.scad>\n\
         include <connectors.scad>\n\n\
         {slices}{body}"
    ))
}

/// The onion connectors on `axis` as a SCAD list `[[cut_pos, a, b, d, ox, oy, oz, ang], ...]` for
/// `slice()`'s `connectors` param — applied per piece (peg into the lower, socket out of the
/// upper). `(ox,oy,oz)` is the onion's cap axis + `ang` its cap angle, DERIVED per joint from the
/// two bordering pieces' print orientations. Phase B: cap axis = the cut axis, ang = 45 (today's
/// behaviour); Phase C swaps in the orientation gate. Errors on a bad cut index.
fn onion_param(s: &Slicing, axis: usize) -> Result<String> {
    let mut items = Vec::new();
    for c in s.connector.iter().filter(|c| c.kind == "onion") {
        let cut = s.cut.get(c.cut).with_context(|| {
            format!("connector references cut {}, but there are {} cut(s)", c.cut, s.cut.len())
        })?;
        if cut.axis_index()? != axis {
            continue;
        }
        // Cap axis = the cut-axis unit (Phase B); ang = 45.
        let unit = |a: usize| if a == axis { 1.0 } else { 0.0 };
        items.push(format!(
            "[{}, {}, {}, {}, {}, {}, {}, {}]",
            n(cut.at()),
            n(c.pos[0].f()),
            n(c.pos[1].f()),
            n(c.size.unwrap_or(10.0)),
            n(unit(0)),
            n(unit(1)),
            n(unit(2)),
            n(45.0)
        ));
    }
    Ok(format!("[{}]", items.join(", ")))
}

/// One `tag("remove") <connector>` line, positioned on its cut plane and oriented along the
/// cut axis (so it slices into both pieces correctly).
fn connector_line(s: &Slicing, c: &Connector) -> Result<String> {
    let cut = s.cut.get(c.cut).with_context(|| {
        format!("connector references cut {}, but there are {} cut(s)", c.cut, s.cut.len())
    })?;
    let ai = cut.axis_index()?;
    // Point = `at` along the cut axis, `pos` in the two perpendicular dims.
    let mut p = [0.0_f64; 3];
    p[ai] = cut.at();
    let others: Vec<usize> = (0..3).filter(|&a| a != ai).collect();
    p[others[0]] = c.pos[0].f();
    p[others[1]] = c.pos[1].f();

    let conn = match c.kind.as_str() {
        "bolt" => format!(
            "bolt_joint(\"{}\", through = {}, orient = {})",
            c.screw.as_deref().unwrap_or("M3"),
            n(c.through.unwrap_or(12.0)),
            AXIS[ai]
        ),
        "pin" => format!("pin_joint(orient = {})", AXIS[ai]),
        other => bail!("connector type must be 'bolt' or 'pin', got '{other}'"),
    };
    Ok(format!(
        "    translate([{}, {}, {}]) tag(\"remove\") {conn};\n",
        n(p[0]),
        n(p[1]),
        n(p[2])
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Manifest;

    fn spec(toml: &str) -> Slicing {
        let m: Manifest = ::toml::from_str(toml).unwrap();
        m.slicing.unwrap()
    }

    #[test]
    fn cuts_group_by_axis_and_sort() {
        let s = spec(
            "[project]\nname=\"t\"\n[slicing]\n\
             [[slicing.cut]]\naxis=\"x\"\nat=25\n\
             [[slicing.cut]]\naxis=\"x\"\nat=-10\n",
        );
        let d = driver_scad(&s, "t.stl", 0.0).unwrap();
        assert!(d.contains("slice([-10, 25], axis = RIGHT, spread = 0, connectors = [])"), "{d}");
        // force_tag() is load-bearing: without it diff() won't carve connectors from the import.
        assert!(d.contains("force_tag() import(\"t.stl\")"), "{d}");
        assert!(d.contains("tag_scope() diff()"));
    }

    #[test]
    fn bolt_connector_positioned_and_oriented() {
        let s = spec(
            "[project]\nname=\"t\"\n[slicing]\n\
             [[slicing.cut]]\naxis=\"z\"\nat=0\n\
             [[slicing.connector]]\ncut=0\ntype=\"bolt\"\nscrew=\"M4\"\npos=[5,-3]\nthrough=15\n",
        );
        let d = driver_scad(&s, "t.stl", 0.0).unwrap();
        // cut on Z -> point is (pos.x, pos.y, at), oriented UP
        assert!(
            d.contains("translate([5, -3, 0]) tag(\"remove\") bolt_joint(\"M4\", through = 15, orient = UP)"),
            "{d}"
        );
    }

    #[test]
    fn onion_rides_the_slice_param_not_the_diff() {
        let s = spec(
            "[project]\nname=\"t\"\n[slicing]\n\
             [[slicing.cut]]\naxis=\"z\"\nat=0\n\
             [[slicing.connector]]\ncut=0\ntype=\"onion\"\npos=[5,-3]\nsize=12\n",
        );
        let d = driver_scad(&s, "t.stl", 30.0).unwrap();
        // Z cut -> others (x,y); onion enters slice()'s connectors param as [at,a,b,d,ox,oy,oz,ang],
        // cap axis = the cut axis (+Z) at Phase B.
        assert!(d.contains("connectors = [[0, 5, -3, 12, 0, 0, 1, 45]]"), "{d}");
        // ...and is NOT emitted as a pre-slice remove in the diff body.
        assert!(!d.contains("onion_"), "{d}");
    }

    #[test]
    fn spread_threads_through() {
        let s = spec("[project]\nname=\"t\"\n[slicing]\n[[slicing.cut]]\naxis=\"y\"\nat=0\n");
        let d = driver_scad(&s, "t.stl", 40.0).unwrap();
        assert!(d.contains("axis = BACK, spread = 40"), "{d}");
    }

    #[test]
    fn no_cuts_errors() {
        let s = spec("[project]\nname=\"t\"\n[slicing]\n");
        assert!(driver_scad(&s, "t.stl", 0.0).is_err());
    }

    #[test]
    fn bad_connector_cut_index_errors() {
        let s = spec(
            "[project]\nname=\"t\"\n[slicing]\n\
             [[slicing.cut]]\naxis=\"x\"\nat=0\n\
             [[slicing.connector]]\ncut=5\ntype=\"pin\"\n",
        );
        assert!(driver_scad(&s, "t.stl", 0.0).is_err());
    }
}
